//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5456.
// 
#pragma warning disable 1591

namespace ConApp_VS2k8.Srv2 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Srv2Soap", Namespace="Srv2")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Srv2ResultBase))]
    public partial class Srv2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveSurveyStructureOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSurveyResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Srv2() {
            this.Url = global::ConApp_VS2k8.Properties.Settings.Default.ConApp_VS2k8_Srv2_Srv2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveSurveyStructureCompletedEventHandler SaveSurveyStructureCompleted;
        
        /// <remarks/>
        public event SaveSurveyResultCompletedEventHandler SaveSurveyResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Srv2/SaveSurveyStructure", RequestNamespace="Srv2", ResponseNamespace="Srv2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SaveSurveyStructureResult SaveSurveyStructure(SurveyStructureDef surveyDef) {
            object[] results = this.Invoke("SaveSurveyStructure", new object[] {
                        surveyDef});
            return ((SaveSurveyStructureResult)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSurveyStructureAsync(SurveyStructureDef surveyDef) {
            this.SaveSurveyStructureAsync(surveyDef, null);
        }
        
        /// <remarks/>
        public void SaveSurveyStructureAsync(SurveyStructureDef surveyDef, object userState) {
            if ((this.SaveSurveyStructureOperationCompleted == null)) {
                this.SaveSurveyStructureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSurveyStructureOperationCompleted);
            }
            this.InvokeAsync("SaveSurveyStructure", new object[] {
                        surveyDef}, this.SaveSurveyStructureOperationCompleted, userState);
        }
        
        private void OnSaveSurveyStructureOperationCompleted(object arg) {
            if ((this.SaveSurveyStructureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSurveyStructureCompleted(this, new SaveSurveyStructureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Srv2/SaveSurveyResult", RequestNamespace="Srv2", ResponseNamespace="Srv2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SaveSurveyResult SaveSurveyResult(SurveyResult surveyResult) {
            object[] results = this.Invoke("SaveSurveyResult", new object[] {
                        surveyResult});
            return ((SaveSurveyResult)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSurveyResultAsync(SurveyResult surveyResult) {
            this.SaveSurveyResultAsync(surveyResult, null);
        }
        
        /// <remarks/>
        public void SaveSurveyResultAsync(SurveyResult surveyResult, object userState) {
            if ((this.SaveSurveyResultOperationCompleted == null)) {
                this.SaveSurveyResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSurveyResultOperationCompleted);
            }
            this.InvokeAsync("SaveSurveyResult", new object[] {
                        surveyResult}, this.SaveSurveyResultOperationCompleted, userState);
        }
        
        private void OnSaveSurveyResultOperationCompleted(object arg) {
            if ((this.SaveSurveyResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSurveyResultCompleted(this, new SaveSurveyResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Srv2")]
    public partial class SurveyStructureDef {
        
        private long surveyIdField;
        
        private string nameField;
        
        private long corporaiotnIdField;
        
        private Question[] questionsField;
        
        private Prompt[] promptsField;
        
        /// <remarks/>
        public long SurveyId {
            get {
                return this.surveyIdField;
            }
            set {
                this.surveyIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public long CorporaiotnId {
            get {
                return this.corporaiotnIdField;
            }
            set {
                this.corporaiotnIdField = value;
            }
        }
        
        /// <remarks/>
        public Question[] Questions {
            get {
                return this.questionsField;
            }
            set {
                this.questionsField = value;
            }
        }
        
        /// <remarks/>
        public Prompt[] Prompts {
            get {
                return this.promptsField;
            }
            set {
                this.promptsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Srv2")]
    public partial class Question {
        
        private long questionIdField;
        
        private string textField;
        
        private long orderField;
        
        private bool isRequiredField;
        
        private int questionTypeIdField;
        
        private int answerTypeIdField;
        
        private Answer[] answersField;
        
        /// <remarks/>
        public long QuestionId {
            get {
                return this.questionIdField;
            }
            set {
                this.questionIdField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public long Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        public int QuestionTypeId {
            get {
                return this.questionTypeIdField;
            }
            set {
                this.questionTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public int AnswerTypeId {
            get {
                return this.answerTypeIdField;
            }
            set {
                this.answerTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public Answer[] Answers {
            get {
                return this.answersField;
            }
            set {
                this.answersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Srv2")]
    public partial class Answer {
        
        private long answerIdField;
        
        private string contentField;
        
        private long orderField;
        
        /// <remarks/>
        public long AnswerId {
            get {
                return this.answerIdField;
            }
            set {
                this.answerIdField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public long Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Srv2")]
    public partial class QuestionResult {
        
        private long questionIdField;
        
        private System.Nullable<long> answerIdField;
        
        private byte wasDisplayedField;
        
        private byte answeredField;
        
        private string contentField;
        
        /// <remarks/>
        public long QuestionId {
            get {
                return this.questionIdField;
            }
            set {
                this.questionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> AnswerId {
            get {
                return this.answerIdField;
            }
            set {
                this.answerIdField = value;
            }
        }
        
        /// <remarks/>
        public byte WasDisplayed {
            get {
                return this.wasDisplayedField;
            }
            set {
                this.wasDisplayedField = value;
            }
        }
        
        /// <remarks/>
        public byte Answered {
            get {
                return this.answeredField;
            }
            set {
                this.answeredField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Srv2")]
    public partial class PromptResult {
        
        private long promptIdField;
        
        private long validationTableItemIdField;
        
        private byte wasDisplayedField;
        
        private byte answeredField;
        
        private string contentField;
        
        /// <remarks/>
        public long PromptId {
            get {
                return this.promptIdField;
            }
            set {
                this.promptIdField = value;
            }
        }
        
        /// <remarks/>
        public long ValidationTableItemId {
            get {
                return this.validationTableItemIdField;
            }
            set {
                this.validationTableItemIdField = value;
            }
        }
        
        /// <remarks/>
        public byte WasDisplayed {
            get {
                return this.wasDisplayedField;
            }
            set {
                this.wasDisplayedField = value;
            }
        }
        
        /// <remarks/>
        public byte Answered {
            get {
                return this.answeredField;
            }
            set {
                this.answeredField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Srv2")]
    public partial class SurveyResult {
        
        private long surveyResultIdField;
        
        private long surveyIdField;
        
        private long locationIdField;
        
        private System.DateTime startDateField;
        
        private System.DateTime startDateUtcField;
        
        private int durationField;
        
        private PromptResult[] promptResultsField;
        
        private QuestionResult[] questionResultsField;
        
        /// <remarks/>
        public long SurveyResultId {
            get {
                return this.surveyResultIdField;
            }
            set {
                this.surveyResultIdField = value;
            }
        }
        
        /// <remarks/>
        public long SurveyId {
            get {
                return this.surveyIdField;
            }
            set {
                this.surveyIdField = value;
            }
        }
        
        /// <remarks/>
        public long LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDateUtc {
            get {
                return this.startDateUtcField;
            }
            set {
                this.startDateUtcField = value;
            }
        }
        
        /// <remarks/>
        public int Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public PromptResult[] PromptResults {
            get {
                return this.promptResultsField;
            }
            set {
                this.promptResultsField = value;
            }
        }
        
        /// <remarks/>
        public QuestionResult[] QuestionResults {
            get {
                return this.questionResultsField;
            }
            set {
                this.questionResultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SaveSurveyResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SaveSurveyStructureResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Srv2")]
    public partial class Srv2ResultBase {
        
        private long resultCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public long ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Srv2")]
    public partial class SaveSurveyResult : Srv2ResultBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Srv2")]
    public partial class SaveSurveyStructureResult : Srv2ResultBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Srv2")]
    public partial class Prompt {
        
        private long promptIdField;
        
        private string textField;
        
        private long orderField;
        
        private long validationTableIdField;
        
        /// <remarks/>
        public long PromptId {
            get {
                return this.promptIdField;
            }
            set {
                this.promptIdField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public long Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public long ValidationTableId {
            get {
                return this.validationTableIdField;
            }
            set {
                this.validationTableIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveSurveyStructureCompletedEventHandler(object sender, SaveSurveyStructureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSurveyStructureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSurveyStructureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveSurveyStructureResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveSurveyStructureResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveSurveyResultCompletedEventHandler(object sender, SaveSurveyResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSurveyResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSurveyResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveSurveyResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveSurveyResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591