//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5456.
// 
#pragma warning disable 1591

namespace ConApp_VS2k8.GuestConnect {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GuestConnectSoap", Namespace="GuestConnect")]
    public partial class GuestConnect : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveGuestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGuestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PageGuestOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveConfigurationOperationCompleted;
        
        private System.Threading.SendOrPostCallback RestoreConfigurationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompanyLogoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompanyInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTablesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GuestConnect() {
            this.Url = global::ConApp_VS2k8.Properties.Settings.Default.ConApp_VS2k8_GuestConnect_GuestConnect;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveGuestCompletedEventHandler SaveGuestCompleted;
        
        /// <remarks/>
        public event GetGuestsCompletedEventHandler GetGuestsCompleted;
        
        /// <remarks/>
        public event SendSmsCompletedEventHandler SendSmsCompleted;
        
        /// <remarks/>
        public event PageGuestCompletedEventHandler PageGuestCompleted;
        
        /// <remarks/>
        public event SaveConfigurationCompletedEventHandler SaveConfigurationCompleted;
        
        /// <remarks/>
        public event RestoreConfigurationCompletedEventHandler RestoreConfigurationCompleted;
        
        /// <remarks/>
        public event GetCompanyLogoCompletedEventHandler GetCompanyLogoCompleted;
        
        /// <remarks/>
        public event GetCompanyInfoCompletedEventHandler GetCompanyInfoCompleted;
        
        /// <remarks/>
        public event SaveTableCompletedEventHandler SaveTableCompleted;
        
        /// <remarks/>
        public event GetTablesCompletedEventHandler GetTablesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GuestConnect/SaveGuest", RequestNamespace="GuestConnect", ResponseNamespace="GuestConnect", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfSaveGuestStatus SaveGuest(string guid, string version, Guest guest) {
            object[] results = this.Invoke("SaveGuest", new object[] {
                        guid,
                        version,
                        guest});
            return ((ActionReturnOfSaveGuestStatus)(results[0]));
        }
        
        /// <remarks/>
        public void SaveGuestAsync(string guid, string version, Guest guest) {
            this.SaveGuestAsync(guid, version, guest, null);
        }
        
        /// <remarks/>
        public void SaveGuestAsync(string guid, string version, Guest guest, object userState) {
            if ((this.SaveGuestOperationCompleted == null)) {
                this.SaveGuestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveGuestOperationCompleted);
            }
            this.InvokeAsync("SaveGuest", new object[] {
                        guid,
                        version,
                        guest}, this.SaveGuestOperationCompleted, userState);
        }
        
        private void OnSaveGuestOperationCompleted(object arg) {
            if ((this.SaveGuestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveGuestCompleted(this, new SaveGuestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GuestConnect/GetGuests", RequestNamespace="GuestConnect", ResponseNamespace="GuestConnect", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfGetGuestsReturn GetGuests(string guid, string version, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> lastSyncTime) {
            object[] results = this.Invoke("GetGuests", new object[] {
                        guid,
                        version,
                        lastSyncTime});
            return ((ActionReturnOfGetGuestsReturn)(results[0]));
        }
        
        /// <remarks/>
        public void GetGuestsAsync(string guid, string version, System.Nullable<System.DateTime> lastSyncTime) {
            this.GetGuestsAsync(guid, version, lastSyncTime, null);
        }
        
        /// <remarks/>
        public void GetGuestsAsync(string guid, string version, System.Nullable<System.DateTime> lastSyncTime, object userState) {
            if ((this.GetGuestsOperationCompleted == null)) {
                this.GetGuestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGuestsOperationCompleted);
            }
            this.InvokeAsync("GetGuests", new object[] {
                        guid,
                        version,
                        lastSyncTime}, this.GetGuestsOperationCompleted, userState);
        }
        
        private void OnGetGuestsOperationCompleted(object arg) {
            if ((this.GetGuestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGuestsCompleted(this, new GetGuestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GuestConnect/SendSms", RequestNamespace="GuestConnect", ResponseNamespace="GuestConnect", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfSendSmsStatus SendSms(string guid, string version, string message, string[] phoneNo) {
            object[] results = this.Invoke("SendSms", new object[] {
                        guid,
                        version,
                        message,
                        phoneNo});
            return ((ActionReturnOfSendSmsStatus)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsAsync(string guid, string version, string message, string[] phoneNo) {
            this.SendSmsAsync(guid, version, message, phoneNo, null);
        }
        
        /// <remarks/>
        public void SendSmsAsync(string guid, string version, string message, string[] phoneNo, object userState) {
            if ((this.SendSmsOperationCompleted == null)) {
                this.SendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsOperationCompleted);
            }
            this.InvokeAsync("SendSms", new object[] {
                        guid,
                        version,
                        message,
                        phoneNo}, this.SendSmsOperationCompleted, userState);
        }
        
        private void OnSendSmsOperationCompleted(object arg) {
            if ((this.SendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsCompleted(this, new SendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GuestConnect/PageGuest", RequestNamespace="GuestConnect", ResponseNamespace="GuestConnect", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfPageGuestStatus PageGuest(string guid, string version, string message, string[] phoneNo) {
            object[] results = this.Invoke("PageGuest", new object[] {
                        guid,
                        version,
                        message,
                        phoneNo});
            return ((ActionReturnOfPageGuestStatus)(results[0]));
        }
        
        /// <remarks/>
        public void PageGuestAsync(string guid, string version, string message, string[] phoneNo) {
            this.PageGuestAsync(guid, version, message, phoneNo, null);
        }
        
        /// <remarks/>
        public void PageGuestAsync(string guid, string version, string message, string[] phoneNo, object userState) {
            if ((this.PageGuestOperationCompleted == null)) {
                this.PageGuestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPageGuestOperationCompleted);
            }
            this.InvokeAsync("PageGuest", new object[] {
                        guid,
                        version,
                        message,
                        phoneNo}, this.PageGuestOperationCompleted, userState);
        }
        
        private void OnPageGuestOperationCompleted(object arg) {
            if ((this.PageGuestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PageGuestCompleted(this, new PageGuestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GuestConnect/SaveConfiguration", RequestNamespace="GuestConnect", ResponseNamespace="GuestConnect", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfSaveConfigStatus SaveConfiguration(string guid, string version, string configuration) {
            object[] results = this.Invoke("SaveConfiguration", new object[] {
                        guid,
                        version,
                        configuration});
            return ((ActionReturnOfSaveConfigStatus)(results[0]));
        }
        
        /// <remarks/>
        public void SaveConfigurationAsync(string guid, string version, string configuration) {
            this.SaveConfigurationAsync(guid, version, configuration, null);
        }
        
        /// <remarks/>
        public void SaveConfigurationAsync(string guid, string version, string configuration, object userState) {
            if ((this.SaveConfigurationOperationCompleted == null)) {
                this.SaveConfigurationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveConfigurationOperationCompleted);
            }
            this.InvokeAsync("SaveConfiguration", new object[] {
                        guid,
                        version,
                        configuration}, this.SaveConfigurationOperationCompleted, userState);
        }
        
        private void OnSaveConfigurationOperationCompleted(object arg) {
            if ((this.SaveConfigurationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveConfigurationCompleted(this, new SaveConfigurationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GuestConnect/RestoreConfiguration", RequestNamespace="GuestConnect", ResponseNamespace="GuestConnect", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfRestoreConfigurationReturn RestoreConfiguration(string guid, string version) {
            object[] results = this.Invoke("RestoreConfiguration", new object[] {
                        guid,
                        version});
            return ((ActionReturnOfRestoreConfigurationReturn)(results[0]));
        }
        
        /// <remarks/>
        public void RestoreConfigurationAsync(string guid, string version) {
            this.RestoreConfigurationAsync(guid, version, null);
        }
        
        /// <remarks/>
        public void RestoreConfigurationAsync(string guid, string version, object userState) {
            if ((this.RestoreConfigurationOperationCompleted == null)) {
                this.RestoreConfigurationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRestoreConfigurationOperationCompleted);
            }
            this.InvokeAsync("RestoreConfiguration", new object[] {
                        guid,
                        version}, this.RestoreConfigurationOperationCompleted, userState);
        }
        
        private void OnRestoreConfigurationOperationCompleted(object arg) {
            if ((this.RestoreConfigurationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RestoreConfigurationCompleted(this, new RestoreConfigurationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GuestConnect/GetCompanyLogo", RequestNamespace="GuestConnect", ResponseNamespace="GuestConnect", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfGetCompanyLogoReturn GetCompanyLogo(string guid, string version) {
            object[] results = this.Invoke("GetCompanyLogo", new object[] {
                        guid,
                        version});
            return ((ActionReturnOfGetCompanyLogoReturn)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompanyLogoAsync(string guid, string version) {
            this.GetCompanyLogoAsync(guid, version, null);
        }
        
        /// <remarks/>
        public void GetCompanyLogoAsync(string guid, string version, object userState) {
            if ((this.GetCompanyLogoOperationCompleted == null)) {
                this.GetCompanyLogoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompanyLogoOperationCompleted);
            }
            this.InvokeAsync("GetCompanyLogo", new object[] {
                        guid,
                        version}, this.GetCompanyLogoOperationCompleted, userState);
        }
        
        private void OnGetCompanyLogoOperationCompleted(object arg) {
            if ((this.GetCompanyLogoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompanyLogoCompleted(this, new GetCompanyLogoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GuestConnect/GetCompanyInfo", RequestNamespace="GuestConnect", ResponseNamespace="GuestConnect", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfGetCompanyInfoReturn GetCompanyInfo(string guid, string version) {
            object[] results = this.Invoke("GetCompanyInfo", new object[] {
                        guid,
                        version});
            return ((ActionReturnOfGetCompanyInfoReturn)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompanyInfoAsync(string guid, string version) {
            this.GetCompanyInfoAsync(guid, version, null);
        }
        
        /// <remarks/>
        public void GetCompanyInfoAsync(string guid, string version, object userState) {
            if ((this.GetCompanyInfoOperationCompleted == null)) {
                this.GetCompanyInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompanyInfoOperationCompleted);
            }
            this.InvokeAsync("GetCompanyInfo", new object[] {
                        guid,
                        version}, this.GetCompanyInfoOperationCompleted, userState);
        }
        
        private void OnGetCompanyInfoOperationCompleted(object arg) {
            if ((this.GetCompanyInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompanyInfoCompleted(this, new GetCompanyInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GuestConnect/SaveTable", RequestNamespace="GuestConnect", ResponseNamespace="GuestConnect", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfSaveTableStatus SaveTable(string guid, string version, Table table) {
            object[] results = this.Invoke("SaveTable", new object[] {
                        guid,
                        version,
                        table});
            return ((ActionReturnOfSaveTableStatus)(results[0]));
        }
        
        /// <remarks/>
        public void SaveTableAsync(string guid, string version, Table table) {
            this.SaveTableAsync(guid, version, table, null);
        }
        
        /// <remarks/>
        public void SaveTableAsync(string guid, string version, Table table, object userState) {
            if ((this.SaveTableOperationCompleted == null)) {
                this.SaveTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveTableOperationCompleted);
            }
            this.InvokeAsync("SaveTable", new object[] {
                        guid,
                        version,
                        table}, this.SaveTableOperationCompleted, userState);
        }
        
        private void OnSaveTableOperationCompleted(object arg) {
            if ((this.SaveTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveTableCompleted(this, new SaveTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GuestConnect/GetTables", RequestNamespace="GuestConnect", ResponseNamespace="GuestConnect", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfGetTablesReturn GetTables(string guid, string version, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> lastSyncTime) {
            object[] results = this.Invoke("GetTables", new object[] {
                        guid,
                        version,
                        lastSyncTime});
            return ((ActionReturnOfGetTablesReturn)(results[0]));
        }
        
        /// <remarks/>
        public void GetTablesAsync(string guid, string version, System.Nullable<System.DateTime> lastSyncTime) {
            this.GetTablesAsync(guid, version, lastSyncTime, null);
        }
        
        /// <remarks/>
        public void GetTablesAsync(string guid, string version, System.Nullable<System.DateTime> lastSyncTime, object userState) {
            if ((this.GetTablesOperationCompleted == null)) {
                this.GetTablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTablesOperationCompleted);
            }
            this.InvokeAsync("GetTables", new object[] {
                        guid,
                        version,
                        lastSyncTime}, this.GetTablesOperationCompleted, userState);
        }
        
        private void OnGetTablesOperationCompleted(object arg) {
            if ((this.GetTablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTablesCompleted(this, new GetTablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class Guest {
        
        private System.Nullable<long> idField;
        
        private string notesField;
        
        private System.Nullable<System.DateTime> timeInField;
        
        private System.Nullable<System.DateTime> pageTimeField;
        
        private System.Nullable<System.DateTime> seatTimeField;
        
        private System.Nullable<System.DateTime> reservationTimeField;
        
        private System.Nullable<DictReservationStatus> reservationStatusField;
        
        private System.Nullable<int> estWaitTimeField;
        
        private int noShowField;
        
        private System.Nullable<Smoking> smokingField;
        
        private string seatingPreferencesField;
        
        private string localUIDField;
        
        private System.Nullable<long> tableIdField;
        
        private string nameField;
        
        private DictReceiverType receiverTypeField;
        
        private string receiverNoField;
        
        private int sizeField;
        
        private bool isVipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TimeIn {
            get {
                return this.timeInField;
            }
            set {
                this.timeInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PageTime {
            get {
                return this.pageTimeField;
            }
            set {
                this.pageTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SeatTime {
            get {
                return this.seatTimeField;
            }
            set {
                this.seatTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReservationTime {
            get {
                return this.reservationTimeField;
            }
            set {
                this.reservationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<DictReservationStatus> ReservationStatus {
            get {
                return this.reservationStatusField;
            }
            set {
                this.reservationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> EstWaitTime {
            get {
                return this.estWaitTimeField;
            }
            set {
                this.estWaitTimeField = value;
            }
        }
        
        /// <remarks/>
        public int NoShow {
            get {
                return this.noShowField;
            }
            set {
                this.noShowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Smoking> Smoking {
            get {
                return this.smokingField;
            }
            set {
                this.smokingField = value;
            }
        }
        
        /// <remarks/>
        public string SeatingPreferences {
            get {
                return this.seatingPreferencesField;
            }
            set {
                this.seatingPreferencesField = value;
            }
        }
        
        /// <remarks/>
        public string LocalUID {
            get {
                return this.localUIDField;
            }
            set {
                this.localUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> TableId {
            get {
                return this.tableIdField;
            }
            set {
                this.tableIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DictReceiverType ReceiverType {
            get {
                return this.receiverTypeField;
            }
            set {
                this.receiverTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReceiverNo {
            get {
                return this.receiverNoField;
            }
            set {
                this.receiverNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsVip {
            get {
                return this.isVipField;
            }
            set {
                this.isVipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum DictReservationStatus {
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Canceled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum Smoking {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum DictReceiverType {
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        Phone,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class GetTablesReturn {
        
        private GetTablesStatus statusField;
        
        private Table[] tablesField;
        
        private System.DateTime currentSyncDateField;
        
        /// <remarks/>
        public GetTablesStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public Table[] Tables {
            get {
                return this.tablesField;
            }
            set {
                this.tablesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CurrentSyncDate {
            get {
                return this.currentSyncDateField;
            }
            set {
                this.currentSyncDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum GetTablesStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        GuidNotFound,
        
        /// <remarks/>
        RestaurantInactive,
        
        /// <remarks/>
        ProductInactive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class Table {
        
        private System.Nullable<long> idField;
        
        private string nameField;
        
        private DictGcTableStatus tableStatusField;
        
        private System.DateTime lastChangeStatusTimeField;
        
        private bool lockRequestedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DictGcTableStatus TableStatus {
            get {
                return this.tableStatusField;
            }
            set {
                this.tableStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime LastChangeStatusTime {
            get {
                return this.lastChangeStatusTimeField;
            }
            set {
                this.lastChangeStatusTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool LockRequested {
            get {
                return this.lockRequestedField;
            }
            set {
                this.lockRequestedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum DictGcTableStatus {
        
        /// <remarks/>
        open,
        
        /// <remarks/>
        hold,
        
        /// <remarks/>
        bussed,
        
        /// <remarks/>
        seated,
        
        /// <remarks/>
        closed,
        
        /// <remarks/>
        deleted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class ActionReturnOfGetTablesReturn {
        
        private GetTablesReturn addDataField;
        
        private ActionReturnStatusEnumOfGetTablesReturn statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public GetTablesReturn AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfGetTablesReturn Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum ActionReturnStatusEnumOfGetTablesReturn {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class ActionReturnOfSaveTableStatus {
        
        private SaveTableStatus addDataField;
        
        private ActionReturnStatusEnumOfSaveTableStatus statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public SaveTableStatus AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfSaveTableStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum SaveTableStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        GuidNotFound,
        
        /// <remarks/>
        RestaurantInactive,
        
        /// <remarks/>
        ProductInactive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum ActionReturnStatusEnumOfSaveTableStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class GetCompanyInfoReturn {
        
        private GlobalStatus statusField;
        
        private string corporationNameField;
        
        private string companyNameField;
        
        /// <remarks/>
        public GlobalStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string CorporationName {
            get {
                return this.corporationNameField;
            }
            set {
                this.corporationNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum GlobalStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        GuidNotFound,
        
        /// <remarks/>
        RestaurantInactive,
        
        /// <remarks/>
        ProductInactive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class ActionReturnOfGetCompanyInfoReturn {
        
        private GetCompanyInfoReturn addDataField;
        
        private ActionReturnStatusEnumOfGetCompanyInfoReturn statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public GetCompanyInfoReturn AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfGetCompanyInfoReturn Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum ActionReturnStatusEnumOfGetCompanyInfoReturn {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class GetCompanyLogoReturn {
        
        private GlobalStatus statusField;
        
        private byte[] fileField;
        
        /// <remarks/>
        public GlobalStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class ActionReturnOfGetCompanyLogoReturn {
        
        private GetCompanyLogoReturn addDataField;
        
        private ActionReturnStatusEnumOfGetCompanyLogoReturn statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public GetCompanyLogoReturn AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfGetCompanyLogoReturn Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum ActionReturnStatusEnumOfGetCompanyLogoReturn {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class RestoreConfigurationReturn {
        
        private RestoreConfigStatus statusField;
        
        private string configurationField;
        
        /// <remarks/>
        public RestoreConfigStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum RestoreConfigStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        GuidNotFound,
        
        /// <remarks/>
        RestaurantInactive,
        
        /// <remarks/>
        ProductInactive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class ActionReturnOfRestoreConfigurationReturn {
        
        private RestoreConfigurationReturn addDataField;
        
        private ActionReturnStatusEnumOfRestoreConfigurationReturn statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public RestoreConfigurationReturn AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfRestoreConfigurationReturn Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum ActionReturnStatusEnumOfRestoreConfigurationReturn {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class ActionReturnOfSaveConfigStatus {
        
        private SaveConfigStatus addDataField;
        
        private ActionReturnStatusEnumOfSaveConfigStatus statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public SaveConfigStatus AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfSaveConfigStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum SaveConfigStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        GuidNotFound,
        
        /// <remarks/>
        RestaurantInactive,
        
        /// <remarks/>
        ProductInactive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum ActionReturnStatusEnumOfSaveConfigStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class ActionReturnOfPageGuestStatus {
        
        private PageGuestStatus addDataField;
        
        private ActionReturnStatusEnumOfPageGuestStatus statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public PageGuestStatus AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfPageGuestStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum PageGuestStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        GuidNotFound,
        
        /// <remarks/>
        RestaurantInactive,
        
        /// <remarks/>
        ProductInactive,
        
        /// <remarks/>
        SmsInactive,
        
        /// <remarks/>
        NotEnoughFunds,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum ActionReturnStatusEnumOfPageGuestStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class ActionReturnOfSendSmsStatus {
        
        private SendSmsStatus addDataField;
        
        private ActionReturnStatusEnumOfSendSmsStatus statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public SendSmsStatus AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfSendSmsStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum SendSmsStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        GuidNotFound,
        
        /// <remarks/>
        RestaurantInactive,
        
        /// <remarks/>
        ProductInactive,
        
        /// <remarks/>
        SmsInactive,
        
        /// <remarks/>
        NotEnoughFunds,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum ActionReturnStatusEnumOfSendSmsStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class GetGuestsReturn {
        
        private GetGuestsStatus statusField;
        
        private Guest[] guestsField;
        
        private System.DateTime currentSyncDateField;
        
        /// <remarks/>
        public GetGuestsStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public Guest[] Guests {
            get {
                return this.guestsField;
            }
            set {
                this.guestsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CurrentSyncDate {
            get {
                return this.currentSyncDateField;
            }
            set {
                this.currentSyncDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum GetGuestsStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        GuidNotFound,
        
        /// <remarks/>
        RestaurantInactive,
        
        /// <remarks/>
        ProductInactive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class ActionReturnOfGetGuestsReturn {
        
        private GetGuestsReturn addDataField;
        
        private ActionReturnStatusEnumOfGetGuestsReturn statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public GetGuestsReturn AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfGetGuestsReturn Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum ActionReturnStatusEnumOfGetGuestsReturn {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public partial class ActionReturnOfSaveGuestStatus {
        
        private SaveGuestStatus addDataField;
        
        private ActionReturnStatusEnumOfSaveGuestStatus statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public SaveGuestStatus AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfSaveGuestStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum SaveGuestStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        GuidNotFound,
        
        /// <remarks/>
        RestaurantInactive,
        
        /// <remarks/>
        ProductInactive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GuestConnect")]
    public enum ActionReturnStatusEnumOfSaveGuestStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveGuestCompletedEventHandler(object sender, SaveGuestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveGuestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveGuestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfSaveGuestStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfSaveGuestStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetGuestsCompletedEventHandler(object sender, GetGuestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGuestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGuestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfGetGuestsReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfGetGuestsReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendSmsCompletedEventHandler(object sender, SendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfSendSmsStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfSendSmsStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void PageGuestCompletedEventHandler(object sender, PageGuestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PageGuestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PageGuestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfPageGuestStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfPageGuestStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveConfigurationCompletedEventHandler(object sender, SaveConfigurationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveConfigurationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveConfigurationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfSaveConfigStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfSaveConfigStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void RestoreConfigurationCompletedEventHandler(object sender, RestoreConfigurationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RestoreConfigurationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RestoreConfigurationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfRestoreConfigurationReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfRestoreConfigurationReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetCompanyLogoCompletedEventHandler(object sender, GetCompanyLogoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompanyLogoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompanyLogoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfGetCompanyLogoReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfGetCompanyLogoReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetCompanyInfoCompletedEventHandler(object sender, GetCompanyInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompanyInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompanyInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfGetCompanyInfoReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfGetCompanyInfoReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveTableCompletedEventHandler(object sender, SaveTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfSaveTableStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfSaveTableStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetTablesCompletedEventHandler(object sender, GetTablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfGetTablesReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfGetTablesReturn)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591