//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5446.
// 
#pragma warning disable 1591

namespace ConApp_VS2k8.ws {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LenovoSoap", Namespace="Lenovo")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SyncBaseObj))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Lenovo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LocationCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConfigOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConfig2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIncommingSmsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Lenovo() {
            this.Url = global::ConApp_VS2k8.Properties.Settings.Default.ConApp_VS2k8_ws_Lenovo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LocationCheckCompletedEventHandler LocationCheckCompleted;
        
        /// <remarks/>
        public event GetConfigCompletedEventHandler GetConfigCompleted;
        
        /// <remarks/>
        public event GetConfig2CompletedEventHandler GetConfig2Completed;
        
        /// <remarks/>
        public event SendSmsCompletedEventHandler SendSmsCompleted;
        
        /// <remarks/>
        public event GetIncommingSmsCompletedEventHandler GetIncommingSmsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Lenovo/LocationCheck", RequestNamespace="Lenovo", ResponseNamespace="Lenovo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfLocationInfo LocationCheck(string guid, string version) {
            object[] results = this.Invoke("LocationCheck", new object[] {
                        guid,
                        version});
            return ((ActionReturnOfLocationInfo)(results[0]));
        }
        
        /// <remarks/>
        public void LocationCheckAsync(string guid, string version) {
            this.LocationCheckAsync(guid, version, null);
        }
        
        /// <remarks/>
        public void LocationCheckAsync(string guid, string version, object userState) {
            if ((this.LocationCheckOperationCompleted == null)) {
                this.LocationCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLocationCheckOperationCompleted);
            }
            this.InvokeAsync("LocationCheck", new object[] {
                        guid,
                        version}, this.LocationCheckOperationCompleted, userState);
        }
        
        private void OnLocationCheckOperationCompleted(object arg) {
            if ((this.LocationCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LocationCheckCompleted(this, new LocationCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Lenovo/GetConfig", RequestNamespace="Lenovo", ResponseNamespace="Lenovo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfLocationConfig GetConfig(string guid) {
            object[] results = this.Invoke("GetConfig", new object[] {
                        guid});
            return ((ActionReturnOfLocationConfig)(results[0]));
        }
        
        /// <remarks/>
        public void GetConfigAsync(string guid) {
            this.GetConfigAsync(guid, null);
        }
        
        /// <remarks/>
        public void GetConfigAsync(string guid, object userState) {
            if ((this.GetConfigOperationCompleted == null)) {
                this.GetConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConfigOperationCompleted);
            }
            this.InvokeAsync("GetConfig", new object[] {
                        guid}, this.GetConfigOperationCompleted, userState);
        }
        
        private void OnGetConfigOperationCompleted(object arg) {
            if ((this.GetConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConfigCompleted(this, new GetConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Lenovo/GetConfig2", RequestNamespace="Lenovo", ResponseNamespace="Lenovo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfLocationSyncConfig GetConfig2(string guid, object[] syncList) {
            object[] results = this.Invoke("GetConfig2", new object[] {
                        guid,
                        syncList});
            return ((ActionReturnOfLocationSyncConfig)(results[0]));
        }
        
        /// <remarks/>
        public void GetConfig2Async(string guid, object[] syncList) {
            this.GetConfig2Async(guid, syncList, null);
        }
        
        /// <remarks/>
        public void GetConfig2Async(string guid, object[] syncList, object userState) {
            if ((this.GetConfig2OperationCompleted == null)) {
                this.GetConfig2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConfig2OperationCompleted);
            }
            this.InvokeAsync("GetConfig2", new object[] {
                        guid,
                        syncList}, this.GetConfig2OperationCompleted, userState);
        }
        
        private void OnGetConfig2OperationCompleted(object arg) {
            if ((this.GetConfig2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConfig2Completed(this, new GetConfig2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Lenovo/SendSms", RequestNamespace="Lenovo", ResponseNamespace="Lenovo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfSendSmsReturnValues SendSms(string guid, string phoneNo, string message) {
            object[] results = this.Invoke("SendSms", new object[] {
                        guid,
                        phoneNo,
                        message});
            return ((ActionReturnOfSendSmsReturnValues)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsAsync(string guid, string phoneNo, string message) {
            this.SendSmsAsync(guid, phoneNo, message, null);
        }
        
        /// <remarks/>
        public void SendSmsAsync(string guid, string phoneNo, string message, object userState) {
            if ((this.SendSmsOperationCompleted == null)) {
                this.SendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsOperationCompleted);
            }
            this.InvokeAsync("SendSms", new object[] {
                        guid,
                        phoneNo,
                        message}, this.SendSmsOperationCompleted, userState);
        }
        
        private void OnSendSmsOperationCompleted(object arg) {
            if ((this.SendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsCompleted(this, new SendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Lenovo/GetIncommingSms", RequestNamespace="Lenovo", ResponseNamespace="Lenovo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfIncomingSmsList GetIncommingSms(string guid) {
            object[] results = this.Invoke("GetIncommingSms", new object[] {
                        guid});
            return ((ActionReturnOfIncomingSmsList)(results[0]));
        }
        
        /// <remarks/>
        public void GetIncommingSmsAsync(string guid) {
            this.GetIncommingSmsAsync(guid, null);
        }
        
        /// <remarks/>
        public void GetIncommingSmsAsync(string guid, object userState) {
            if ((this.GetIncommingSmsOperationCompleted == null)) {
                this.GetIncommingSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIncommingSmsOperationCompleted);
            }
            this.InvokeAsync("GetIncommingSms", new object[] {
                        guid}, this.GetIncommingSmsOperationCompleted, userState);
        }
        
        private void OnGetIncommingSmsOperationCompleted(object arg) {
            if ((this.GetIncommingSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIncommingSmsCompleted(this, new GetIncommingSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class ActionReturnOfLocationInfo {
        
        private LocationInfo addDataField;
        
        private ActionReturnStatusEnumOfLocationInfo statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public LocationInfo AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfLocationInfo Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class LocationInfo {
        
        private bool locationFoundField;
        
        private System.Nullable<bool> isConfigUpToDateField;
        
        private System.Nullable<double> tokenBalanceField;
        
        private System.Nullable<bool> incomingSmsExistsField;
        
        private bool isManagerPinClearingField;
        
        private string managerPinField;
        
        private string installUrlField;
        
        /// <remarks/>
        public bool LocationFound {
            get {
                return this.locationFoundField;
            }
            set {
                this.locationFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsConfigUpToDate {
            get {
                return this.isConfigUpToDateField;
            }
            set {
                this.isConfigUpToDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> TokenBalance {
            get {
                return this.tokenBalanceField;
            }
            set {
                this.tokenBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IncomingSmsExists {
            get {
                return this.incomingSmsExistsField;
            }
            set {
                this.incomingSmsExistsField = value;
            }
        }
        
        /// <remarks/>
        public bool IsManagerPinClearing {
            get {
                return this.isManagerPinClearingField;
            }
            set {
                this.isManagerPinClearingField = value;
            }
        }
        
        /// <remarks/>
        public string ManagerPin {
            get {
                return this.managerPinField;
            }
            set {
                this.managerPinField = value;
            }
        }
        
        /// <remarks/>
        public string InstallUrl {
            get {
                return this.installUrlField;
            }
            set {
                this.installUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class IncomingSms {
        
        private string messageField;
        
        private WLIncomingSmsType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WLIncomingSmsType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum WLIncomingSmsType {
        
        /// <remarks/>
        Incoming,
        
        /// <remarks/>
        TableClosed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class ActionReturnOfIncomingSmsList {
        
        private IncomingSms[] addDataField;
        
        private ActionReturnStatusEnumOfIncomingSmsList statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public IncomingSms[] AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfIncomingSmsList Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum ActionReturnStatusEnumOfIncomingSmsList {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class ActionReturnOfSendSmsReturnValues {
        
        private SendSmsReturnValues addDataField;
        
        private ActionReturnStatusEnumOfSendSmsReturnValues statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public SendSmsReturnValues AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfSendSmsReturnValues Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum SendSmsReturnValues {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        NotEnoughFunds,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        LocationInactive,
        
        /// <remarks/>
        SmsDisabled,
        
        /// <remarks/>
        LocationNotFound,
        
        /// <remarks/>
        IncorrectPhoneNo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum ActionReturnStatusEnumOfSendSmsReturnValues {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TableSync))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ButtonSync))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class SyncBaseObj {
        
        private System.Nullable<long> wlDbIdField;
        
        private System.Nullable<long> clientIdField;
        
        private System.Nullable<ModifyStatus> modifyStatusField;
        
        private System.Nullable<SyncStatus> syncStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> WlDbId {
            get {
                return this.wlDbIdField;
            }
            set {
                this.wlDbIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<ModifyStatus> ModifyStatus {
            get {
                return this.modifyStatusField;
            }
            set {
                this.modifyStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<SyncStatus> SyncStatus {
            get {
                return this.syncStatusField;
            }
            set {
                this.syncStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum ModifyStatus {
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Modified,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum SyncStatus {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Success,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class TableSync : SyncBaseObj {
        
        private string serialNoField;
        
        private System.Nullable<long> beachButlerWhoToPageField;
        
        private string beachButlerMessageField;
        
        private System.Nullable<long> tGLeftButtonWhoToPageField;
        
        private string tableGenieLeftButtonMessageField;
        
        private System.Nullable<long> tGMiddleButtonWhoToPageField;
        
        private string tableGenieMiddleButtonMessageField;
        
        private System.Nullable<long> tGRightButtonWhoToPageField;
        
        private string tableGenieRightButtonMessageField;
        
        private int numberField;
        
        private long serviceDeviceIdField;
        
        /// <remarks/>
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> BeachButlerWhoToPage {
            get {
                return this.beachButlerWhoToPageField;
            }
            set {
                this.beachButlerWhoToPageField = value;
            }
        }
        
        /// <remarks/>
        public string BeachButlerMessage {
            get {
                return this.beachButlerMessageField;
            }
            set {
                this.beachButlerMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> TGLeftButtonWhoToPage {
            get {
                return this.tGLeftButtonWhoToPageField;
            }
            set {
                this.tGLeftButtonWhoToPageField = value;
            }
        }
        
        /// <remarks/>
        public string TableGenieLeftButtonMessage {
            get {
                return this.tableGenieLeftButtonMessageField;
            }
            set {
                this.tableGenieLeftButtonMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> TGMiddleButtonWhoToPage {
            get {
                return this.tGMiddleButtonWhoToPageField;
            }
            set {
                this.tGMiddleButtonWhoToPageField = value;
            }
        }
        
        /// <remarks/>
        public string TableGenieMiddleButtonMessage {
            get {
                return this.tableGenieMiddleButtonMessageField;
            }
            set {
                this.tableGenieMiddleButtonMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> TGRightButtonWhoToPage {
            get {
                return this.tGRightButtonWhoToPageField;
            }
            set {
                this.tGRightButtonWhoToPageField = value;
            }
        }
        
        /// <remarks/>
        public string TableGenieRightButtonMessage {
            get {
                return this.tableGenieRightButtonMessageField;
            }
            set {
                this.tableGenieRightButtonMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ServiceDeviceId {
            get {
                return this.serviceDeviceIdField;
            }
            set {
                this.serviceDeviceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class ButtonSync : SyncBaseObj {
        
        private string messageTextField;
        
        private string buttonTextField;
        
        private EmployeeType employeeTypeField;
        
        private long buttonOrderField;
        
        private bool isMessageDefinedField;
        
        /// <remarks/>
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ButtonText {
            get {
                return this.buttonTextField;
            }
            set {
                this.buttonTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EmployeeType EmployeeType {
            get {
                return this.employeeTypeField;
            }
            set {
                this.employeeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ButtonOrder {
            get {
                return this.buttonOrderField;
            }
            set {
                this.buttonOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsMessageDefined {
            get {
                return this.isMessageDefinedField;
            }
            set {
                this.isMessageDefinedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum EmployeeType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Waiter,
        
        /// <remarks/>
        Manager,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class LocationSyncConfig {
        
        private object[] syncListField;
        
        private bool isCellPhonePagingEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Buttons", typeof(ButtonSync[]))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(ButtonSync), NestingLevel=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Tables", typeof(TableSync[]))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(TableSync), NestingLevel=1)]
        public object[] SyncList {
            get {
                return this.syncListField;
            }
            set {
                this.syncListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsCellPhonePagingEnabled {
            get {
                return this.isCellPhonePagingEnabledField;
            }
            set {
                this.isCellPhonePagingEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class ActionReturnOfLocationSyncConfig {
        
        private LocationSyncConfig addDataField;
        
        private ActionReturnStatusEnumOfLocationSyncConfig statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public LocationSyncConfig AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfLocationSyncConfig Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum ActionReturnStatusEnumOfLocationSyncConfig {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class WiFi {
        
        private string welcomeMessageField;
        
        private string tableNumberField;
        
        private string tablePromptField;
        
        private string buttonTextField;
        
        private string messageTextField;
        
        private string tableErrorTextField;
        
        private bool isEnableField;
        
        /// <remarks/>
        public string WelcomeMessage {
            get {
                return this.welcomeMessageField;
            }
            set {
                this.welcomeMessageField = value;
            }
        }
        
        /// <remarks/>
        public string TableNumber {
            get {
                return this.tableNumberField;
            }
            set {
                this.tableNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TablePrompt {
            get {
                return this.tablePromptField;
            }
            set {
                this.tablePromptField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonText {
            get {
                return this.buttonTextField;
            }
            set {
                this.buttonTextField = value;
            }
        }
        
        /// <remarks/>
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
            }
        }
        
        /// <remarks/>
        public string TableErrorText {
            get {
                return this.tableErrorTextField;
            }
            set {
                this.tableErrorTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsEnable {
            get {
                return this.isEnableField;
            }
            set {
                this.isEnableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class Button {
        
        private string messageTextField;
        
        private long idField;
        
        private string buttonTextField;
        
        private EmployeeType employeeTypeField;
        
        private long buttonOrderField;
        
        private bool isMessageDefinedField;
        
        /// <remarks/>
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ButtonText {
            get {
                return this.buttonTextField;
            }
            set {
                this.buttonTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EmployeeType EmployeeType {
            get {
                return this.employeeTypeField;
            }
            set {
                this.employeeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ButtonOrder {
            get {
                return this.buttonOrderField;
            }
            set {
                this.buttonOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsMessageDefined {
            get {
                return this.isMessageDefinedField;
            }
            set {
                this.isMessageDefinedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class Employee {
        
        private PageType pageTypeField;
        
        private string phoneField;
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public PageType PageType {
            get {
                return this.pageTypeField;
            }
            set {
                this.pageTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum PageType {
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class Table {
        
        private string serialNoField;
        
        private System.Nullable<long> beachButlerWhoToPageField;
        
        private string beachButlerMessageField;
        
        private System.Nullable<long> tGLeftButtonWhoToPageField;
        
        private string tableGenieLeftButtonMessageField;
        
        private System.Nullable<long> tGMiddleButtonWhoToPageField;
        
        private string tableGenieMiddleButtonMessageField;
        
        private System.Nullable<long> tGRightButtonWhoToPageField;
        
        private string tableGenieRightButtonMessageField;
        
        private long idField;
        
        private int numberField;
        
        private long serviceDeviceIdField;
        
        /// <remarks/>
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> BeachButlerWhoToPage {
            get {
                return this.beachButlerWhoToPageField;
            }
            set {
                this.beachButlerWhoToPageField = value;
            }
        }
        
        /// <remarks/>
        public string BeachButlerMessage {
            get {
                return this.beachButlerMessageField;
            }
            set {
                this.beachButlerMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> TGLeftButtonWhoToPage {
            get {
                return this.tGLeftButtonWhoToPageField;
            }
            set {
                this.tGLeftButtonWhoToPageField = value;
            }
        }
        
        /// <remarks/>
        public string TableGenieLeftButtonMessage {
            get {
                return this.tableGenieLeftButtonMessageField;
            }
            set {
                this.tableGenieLeftButtonMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> TGMiddleButtonWhoToPage {
            get {
                return this.tGMiddleButtonWhoToPageField;
            }
            set {
                this.tGMiddleButtonWhoToPageField = value;
            }
        }
        
        /// <remarks/>
        public string TableGenieMiddleButtonMessage {
            get {
                return this.tableGenieMiddleButtonMessageField;
            }
            set {
                this.tableGenieMiddleButtonMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> TGRightButtonWhoToPage {
            get {
                return this.tGRightButtonWhoToPageField;
            }
            set {
                this.tGRightButtonWhoToPageField = value;
            }
        }
        
        /// <remarks/>
        public string TableGenieRightButtonMessage {
            get {
                return this.tableGenieRightButtonMessageField;
            }
            set {
                this.tableGenieRightButtonMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ServiceDeviceId {
            get {
                return this.serviceDeviceIdField;
            }
            set {
                this.serviceDeviceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class Section {
        
        private System.Nullable<int> colorTimersForWarningField;
        
        private System.Nullable<int> colorTimersForSecondWarningField;
        
        private System.Nullable<int> colorTimersForAlertField;
        
        private System.Nullable<int> pagingManagerSecondsField;
        
        private string pagingManagerMessageField;
        
        private Table[] tablesField;
        
        private long idField;
        
        private string nameField;
        
        private bool colorTimersForWarningIsEnabledField;
        
        private bool colorTimersForSecondWarningIsEnabledField;
        
        private bool colorTimersForAlertIsEnabledField;
        
        private bool pagingManagerIsEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ColorTimersForWarning {
            get {
                return this.colorTimersForWarningField;
            }
            set {
                this.colorTimersForWarningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ColorTimersForSecondWarning {
            get {
                return this.colorTimersForSecondWarningField;
            }
            set {
                this.colorTimersForSecondWarningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ColorTimersForAlert {
            get {
                return this.colorTimersForAlertField;
            }
            set {
                this.colorTimersForAlertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PagingManagerSeconds {
            get {
                return this.pagingManagerSecondsField;
            }
            set {
                this.pagingManagerSecondsField = value;
            }
        }
        
        /// <remarks/>
        public string PagingManagerMessage {
            get {
                return this.pagingManagerMessageField;
            }
            set {
                this.pagingManagerMessageField = value;
            }
        }
        
        /// <remarks/>
        public Table[] Tables {
            get {
                return this.tablesField;
            }
            set {
                this.tablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ColorTimersForWarningIsEnabled {
            get {
                return this.colorTimersForWarningIsEnabledField;
            }
            set {
                this.colorTimersForWarningIsEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ColorTimersForSecondWarningIsEnabled {
            get {
                return this.colorTimersForSecondWarningIsEnabledField;
            }
            set {
                this.colorTimersForSecondWarningIsEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ColorTimersForAlertIsEnabled {
            get {
                return this.colorTimersForAlertIsEnabledField;
            }
            set {
                this.colorTimersForAlertIsEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool PagingManagerIsEnabled {
            get {
                return this.pagingManagerIsEnabledField;
            }
            set {
                this.pagingManagerIsEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class Layout {
        
        private Section[] sectionsField;
        
        private long idField;
        
        private string nameField;
        
        private int isDefaultField;
        
        /// <remarks/>
        public Section[] Sections {
            get {
                return this.sectionsField;
            }
            set {
                this.sectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class LocationConfig {
        
        private Layout[] layoutsField;
        
        private Employee[] employeesField;
        
        private Button[] buttonsField;
        
        private WiFi wifiField;
        
        private bool isCellPhonePagingEnabledField;
        
        /// <remarks/>
        public Layout[] Layouts {
            get {
                return this.layoutsField;
            }
            set {
                this.layoutsField = value;
            }
        }
        
        /// <remarks/>
        public Employee[] Employees {
            get {
                return this.employeesField;
            }
            set {
                this.employeesField = value;
            }
        }
        
        /// <remarks/>
        public Button[] Buttons {
            get {
                return this.buttonsField;
            }
            set {
                this.buttonsField = value;
            }
        }
        
        /// <remarks/>
        public WiFi Wifi {
            get {
                return this.wifiField;
            }
            set {
                this.wifiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsCellPhonePagingEnabled {
            get {
                return this.isCellPhonePagingEnabledField;
            }
            set {
                this.isCellPhonePagingEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public partial class ActionReturnOfLocationConfig {
        
        private LocationConfig addDataField;
        
        private ActionReturnStatusEnumOfLocationConfig statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public LocationConfig AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfLocationConfig Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum ActionReturnStatusEnumOfLocationConfig {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lenovo")]
    public enum ActionReturnStatusEnumOfLocationInfo {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void LocationCheckCompletedEventHandler(object sender, LocationCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LocationCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LocationCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfLocationInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfLocationInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetConfigCompletedEventHandler(object sender, GetConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfLocationConfig Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfLocationConfig)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetConfig2CompletedEventHandler(object sender, GetConfig2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConfig2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConfig2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfLocationSyncConfig Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfLocationSyncConfig)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendSmsCompletedEventHandler(object sender, SendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfSendSmsReturnValues Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfSendSmsReturnValues)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetIncommingSmsCompletedEventHandler(object sender, GetIncommingSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIncommingSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIncommingSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfIncomingSmsList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfIncomingSmsList)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591