//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5448.
// 
#pragma warning disable 1591

namespace ConApp_VS2k8.TT {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TableTrackerSoap", Namespace="http://tempuri.org/")]
    public partial class TableTracker : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveDataAndConfigOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveDataAndConfig2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessage2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TableTracker() {
            this.Url = global::ConApp_VS2k8.Properties.Settings.Default.ConApp_VS2k8_TT_TableTracker;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveDataAndConfigCompletedEventHandler SaveDataAndConfigCompleted;
        
        /// <remarks/>
        public event SaveDataAndConfig2CompletedEventHandler SaveDataAndConfig2Completed;
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        public event SendMessage2CompletedEventHandler SendMessage2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveDataAndConfig", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LRSTablerTrackerResponse SaveDataAndConfig(LRSTablerTrackerRequest request) {
            object[] results = this.Invoke("SaveDataAndConfig", new object[] {
                        request});
            return ((LRSTablerTrackerResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SaveDataAndConfigAsync(LRSTablerTrackerRequest request) {
            this.SaveDataAndConfigAsync(request, null);
        }
        
        /// <remarks/>
        public void SaveDataAndConfigAsync(LRSTablerTrackerRequest request, object userState) {
            if ((this.SaveDataAndConfigOperationCompleted == null)) {
                this.SaveDataAndConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveDataAndConfigOperationCompleted);
            }
            this.InvokeAsync("SaveDataAndConfig", new object[] {
                        request}, this.SaveDataAndConfigOperationCompleted, userState);
        }
        
        private void OnSaveDataAndConfigOperationCompleted(object arg) {
            if ((this.SaveDataAndConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveDataAndConfigCompleted(this, new SaveDataAndConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveDataAndConfig2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LRSTablerTrackerResponse SaveDataAndConfig2(string version, LRSTablerTrackerRequest request) {
            object[] results = this.Invoke("SaveDataAndConfig2", new object[] {
                        version,
                        request});
            return ((LRSTablerTrackerResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SaveDataAndConfig2Async(string version, LRSTablerTrackerRequest request) {
            this.SaveDataAndConfig2Async(version, request, null);
        }
        
        /// <remarks/>
        public void SaveDataAndConfig2Async(string version, LRSTablerTrackerRequest request, object userState) {
            if ((this.SaveDataAndConfig2OperationCompleted == null)) {
                this.SaveDataAndConfig2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveDataAndConfig2OperationCompleted);
            }
            this.InvokeAsync("SaveDataAndConfig2", new object[] {
                        version,
                        request}, this.SaveDataAndConfig2OperationCompleted, userState);
        }
        
        private void OnSaveDataAndConfig2OperationCompleted(object arg) {
            if ((this.SaveDataAndConfig2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveDataAndConfig2Completed(this, new SaveDataAndConfig2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendMessage(string locationUID, string phoneNo, string message) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        locationUID,
                        phoneNo,
                        message});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(string locationUID, string phoneNo, string message) {
            this.SendMessageAsync(locationUID, phoneNo, message, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(string locationUID, string phoneNo, string message, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        locationUID,
                        phoneNo,
                        message}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMessage2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendMessage2(string locationUid, string version, string phoneNo, string message) {
            object[] results = this.Invoke("SendMessage2", new object[] {
                        locationUid,
                        version,
                        phoneNo,
                        message});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessage2Async(string locationUid, string version, string phoneNo, string message) {
            this.SendMessage2Async(locationUid, version, phoneNo, message, null);
        }
        
        /// <remarks/>
        public void SendMessage2Async(string locationUid, string version, string phoneNo, string message, object userState) {
            if ((this.SendMessage2OperationCompleted == null)) {
                this.SendMessage2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessage2OperationCompleted);
            }
            this.InvokeAsync("SendMessage2", new object[] {
                        locationUid,
                        version,
                        phoneNo,
                        message}, this.SendMessage2OperationCompleted, userState);
        }
        
        private void OnSendMessage2OperationCompleted(object arg) {
            if ((this.SendMessage2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessage2Completed(this, new SendMessage2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LRSTablerTrackerRequest {
        
        private string locationUIDField;
        
        private LRSTableTrackerOrderDto[] ordersField;
        
        private LRSTablerTrackerConfigurationDto configurationField;
        
        /// <remarks/>
        public string LocationUID {
            get {
                return this.locationUIDField;
            }
            set {
                this.locationUIDField = value;
            }
        }
        
        /// <remarks/>
        public LRSTableTrackerOrderDto[] Orders {
            get {
                return this.ordersField;
            }
            set {
                this.ordersField = value;
            }
        }
        
        /// <remarks/>
        public LRSTablerTrackerConfigurationDto Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LRSTableTrackerOrderDto {
        
        private int orderNumberField;
        
        private System.Nullable<int> tableNumberField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime endTimeField;
        
        private System.Nullable<int> closedTypeField;
        
        private System.Nullable<System.DateTime> tableTimeField;
        
        private byte wasPageSentField;
        
        private long localIdField;
        
        /// <remarks/>
        public int OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TableNumber {
            get {
                return this.tableNumberField;
            }
            set {
                this.tableNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ClosedType {
            get {
                return this.closedTypeField;
            }
            set {
                this.closedTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TableTime {
            get {
                return this.tableTimeField;
            }
            set {
                this.tableTimeField = value;
            }
        }
        
        /// <remarks/>
        public byte wasPageSent {
            get {
                return this.wasPageSentField;
            }
            set {
                this.wasPageSentField = value;
            }
        }
        
        /// <remarks/>
        public long LocalId {
            get {
                return this.localIdField;
            }
            set {
                this.localIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LRSTablerTrackerResponse {
        
        private long[] succeededOrdersField;
        
        private LRSTableTrackerResult statusField;
        
        /// <remarks/>
        public long[] SucceededOrders {
            get {
                return this.succeededOrdersField;
            }
            set {
                this.succeededOrdersField = value;
            }
        }
        
        /// <remarks/>
        public LRSTableTrackerResult Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LRSTableTrackerResult {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Disabled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LRSTablerTrackerConfigurationDto {
        
        private int warningTimeField;
        
        private byte isWarningTimeField;
        
        private int secondWarningTimeField;
        
        private byte isSecondWarningTimeField;
        
        private int serviceGoalExceededField;
        
        private byte isServiceGoalExceededField;
        
        /// <remarks/>
        public int WarningTime {
            get {
                return this.warningTimeField;
            }
            set {
                this.warningTimeField = value;
            }
        }
        
        /// <remarks/>
        public byte IsWarningTime {
            get {
                return this.isWarningTimeField;
            }
            set {
                this.isWarningTimeField = value;
            }
        }
        
        /// <remarks/>
        public int SecondWarningTime {
            get {
                return this.secondWarningTimeField;
            }
            set {
                this.secondWarningTimeField = value;
            }
        }
        
        /// <remarks/>
        public byte IsSecondWarningTime {
            get {
                return this.isSecondWarningTimeField;
            }
            set {
                this.isSecondWarningTimeField = value;
            }
        }
        
        /// <remarks/>
        public int ServiceGoalExceeded {
            get {
                return this.serviceGoalExceededField;
            }
            set {
                this.serviceGoalExceededField = value;
            }
        }
        
        /// <remarks/>
        public byte IsServiceGoalExceeded {
            get {
                return this.isServiceGoalExceededField;
            }
            set {
                this.isServiceGoalExceededField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveDataAndConfigCompletedEventHandler(object sender, SaveDataAndConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveDataAndConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveDataAndConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LRSTablerTrackerResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LRSTablerTrackerResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveDataAndConfig2CompletedEventHandler(object sender, SaveDataAndConfig2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveDataAndConfig2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveDataAndConfig2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LRSTablerTrackerResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LRSTablerTrackerResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendMessageCompletedEventHandler(object sender, SendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendMessage2CompletedEventHandler(object sender, SendMessage2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessage2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessage2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591