//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5448.
// 
#pragma warning disable 1591

namespace ConApp_VS2k8.SmsProxy {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSMailerSoap", Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class WSMailer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendMailTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveNewPhoneNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemovePhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsCallNeededOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSms2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSms3OperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveNewPhoneNo2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveNewPhoneNo3OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsWithBackupOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveNewPhoneNoWithBackupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearPhoneNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveNewPhoneNoWithBackup2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsWithBackup2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsWithBackupParamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSmsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsPermiumOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsPermiumOperatorOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsPermiumOperator2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSMailer() {
            this.Url = global::ConApp_VS2k8.Properties.Settings.Default.ConApp_VS2k8_SmsProxy_WSMailer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMailTemplateCompletedEventHandler SendMailTemplateCompleted;
        
        /// <remarks/>
        public event SendSmsCompletedEventHandler SendSmsCompleted;
        
        /// <remarks/>
        public event SaveNewPhoneNoCompletedEventHandler SaveNewPhoneNoCompleted;
        
        /// <remarks/>
        public event RemovePhoneNumberCompletedEventHandler RemovePhoneNumberCompleted;
        
        /// <remarks/>
        public event IsCallNeededCompletedEventHandler IsCallNeededCompleted;
        
        /// <remarks/>
        public event SendSms2CompletedEventHandler SendSms2Completed;
        
        /// <remarks/>
        public event SendSms3CompletedEventHandler SendSms3Completed;
        
        /// <remarks/>
        public event SaveNewPhoneNo2CompletedEventHandler SaveNewPhoneNo2Completed;
        
        /// <remarks/>
        public event SaveNewPhoneNo3CompletedEventHandler SaveNewPhoneNo3Completed;
        
        /// <remarks/>
        public event SendSmsWithBackupCompletedEventHandler SendSmsWithBackupCompleted;
        
        /// <remarks/>
        public event SaveNewPhoneNoWithBackupCompletedEventHandler SaveNewPhoneNoWithBackupCompleted;
        
        /// <remarks/>
        public event ClearPhoneNoCompletedEventHandler ClearPhoneNoCompleted;
        
        /// <remarks/>
        public event SaveNewPhoneNoWithBackup2CompletedEventHandler SaveNewPhoneNoWithBackup2Completed;
        
        /// <remarks/>
        public event SendSmsWithBackup2CompletedEventHandler SendSmsWithBackup2Completed;
        
        /// <remarks/>
        public event SendSmsWithBackupParamsCompletedEventHandler SendSmsWithBackupParamsCompleted;
        
        /// <remarks/>
        public event GetSmsListCompletedEventHandler GetSmsListCompleted;
        
        /// <remarks/>
        public event IsPermiumCompletedEventHandler IsPermiumCompleted;
        
        /// <remarks/>
        public event IsPermiumOperatorCompletedEventHandler IsPermiumOperatorCompleted;
        
        /// <remarks/>
        public event IsPermiumOperator2CompletedEventHandler IsPermiumOperator2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SendMailTemplate", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientMailSendReturn SendMailTemplate(ClientSendMailTemplate dto) {
            object[] results = this.Invoke("SendMailTemplate", new object[] {
                        dto});
            return ((ClientMailSendReturn)(results[0]));
        }
        
        /// <remarks/>
        public void SendMailTemplateAsync(ClientSendMailTemplate dto) {
            this.SendMailTemplateAsync(dto, null);
        }
        
        /// <remarks/>
        public void SendMailTemplateAsync(ClientSendMailTemplate dto, object userState) {
            if ((this.SendMailTemplateOperationCompleted == null)) {
                this.SendMailTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailTemplateOperationCompleted);
            }
            this.InvokeAsync("SendMailTemplate", new object[] {
                        dto}, this.SendMailTemplateOperationCompleted, userState);
        }
        
        private void OnSendMailTemplateOperationCompleted(object arg) {
            if ((this.SendMailTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailTemplateCompleted(this, new SendMailTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SendSms", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfBoolean SendSms(string SenderId, string PhoneNo, string Carrier, string message, bool isRequiredEnrollMsg, string EnrollMessage, byte applicationType) {
            object[] results = this.Invoke("SendSms", new object[] {
                        SenderId,
                        PhoneNo,
                        Carrier,
                        message,
                        isRequiredEnrollMsg,
                        EnrollMessage,
                        applicationType});
            return ((ActionReturnOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsAsync(string SenderId, string PhoneNo, string Carrier, string message, bool isRequiredEnrollMsg, string EnrollMessage, byte applicationType) {
            this.SendSmsAsync(SenderId, PhoneNo, Carrier, message, isRequiredEnrollMsg, EnrollMessage, applicationType, null);
        }
        
        /// <remarks/>
        public void SendSmsAsync(string SenderId, string PhoneNo, string Carrier, string message, bool isRequiredEnrollMsg, string EnrollMessage, byte applicationType, object userState) {
            if ((this.SendSmsOperationCompleted == null)) {
                this.SendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsOperationCompleted);
            }
            this.InvokeAsync("SendSms", new object[] {
                        SenderId,
                        PhoneNo,
                        Carrier,
                        message,
                        isRequiredEnrollMsg,
                        EnrollMessage,
                        applicationType}, this.SendSmsOperationCompleted, userState);
        }
        
        private void OnSendSmsOperationCompleted(object arg) {
            if ((this.SendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsCompleted(this, new SendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SaveNewPhoneNo", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfBoolean SaveNewPhoneNo(string SenderId, string PhoneNo, string Carrier, string EnrollMessage, byte applicationType) {
            object[] results = this.Invoke("SaveNewPhoneNo", new object[] {
                        SenderId,
                        PhoneNo,
                        Carrier,
                        EnrollMessage,
                        applicationType});
            return ((ActionReturnOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void SaveNewPhoneNoAsync(string SenderId, string PhoneNo, string Carrier, string EnrollMessage, byte applicationType) {
            this.SaveNewPhoneNoAsync(SenderId, PhoneNo, Carrier, EnrollMessage, applicationType, null);
        }
        
        /// <remarks/>
        public void SaveNewPhoneNoAsync(string SenderId, string PhoneNo, string Carrier, string EnrollMessage, byte applicationType, object userState) {
            if ((this.SaveNewPhoneNoOperationCompleted == null)) {
                this.SaveNewPhoneNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveNewPhoneNoOperationCompleted);
            }
            this.InvokeAsync("SaveNewPhoneNo", new object[] {
                        SenderId,
                        PhoneNo,
                        Carrier,
                        EnrollMessage,
                        applicationType}, this.SaveNewPhoneNoOperationCompleted, userState);
        }
        
        private void OnSaveNewPhoneNoOperationCompleted(object arg) {
            if ((this.SaveNewPhoneNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveNewPhoneNoCompleted(this, new SaveNewPhoneNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/RemovePhoneNumber", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfBoolean RemovePhoneNumber(string PhoneNo) {
            object[] results = this.Invoke("RemovePhoneNumber", new object[] {
                        PhoneNo});
            return ((ActionReturnOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void RemovePhoneNumberAsync(string PhoneNo) {
            this.RemovePhoneNumberAsync(PhoneNo, null);
        }
        
        /// <remarks/>
        public void RemovePhoneNumberAsync(string PhoneNo, object userState) {
            if ((this.RemovePhoneNumberOperationCompleted == null)) {
                this.RemovePhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemovePhoneNumberOperationCompleted);
            }
            this.InvokeAsync("RemovePhoneNumber", new object[] {
                        PhoneNo}, this.RemovePhoneNumberOperationCompleted, userState);
        }
        
        private void OnRemovePhoneNumberOperationCompleted(object arg) {
            if ((this.RemovePhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemovePhoneNumberCompleted(this, new RemovePhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/IsCallNeeded", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfBoolean IsCallNeeded(string phoneNo) {
            object[] results = this.Invoke("IsCallNeeded", new object[] {
                        phoneNo});
            return ((ActionReturnOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void IsCallNeededAsync(string phoneNo) {
            this.IsCallNeededAsync(phoneNo, null);
        }
        
        /// <remarks/>
        public void IsCallNeededAsync(string phoneNo, object userState) {
            if ((this.IsCallNeededOperationCompleted == null)) {
                this.IsCallNeededOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsCallNeededOperationCompleted);
            }
            this.InvokeAsync("IsCallNeeded", new object[] {
                        phoneNo}, this.IsCallNeededOperationCompleted, userState);
        }
        
        private void OnIsCallNeededOperationCompleted(object arg) {
            if ((this.IsCallNeededCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsCallNeededCompleted(this, new IsCallNeededCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SendSms2", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfBoolean SendSms2(string senderId, string phoneNo, string carrier, string message, bool isRequiredEnrollMsg, string enrollMessage, byte applicationType, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out System.Nullable<long> messageId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out System.Nullable<long> enrollMessageId) {
            object[] results = this.Invoke("SendSms2", new object[] {
                        senderId,
                        phoneNo,
                        carrier,
                        message,
                        isRequiredEnrollMsg,
                        enrollMessage,
                        applicationType});
            messageId = ((System.Nullable<long>)(results[1]));
            enrollMessageId = ((System.Nullable<long>)(results[2]));
            return ((ActionReturnOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void SendSms2Async(string senderId, string phoneNo, string carrier, string message, bool isRequiredEnrollMsg, string enrollMessage, byte applicationType) {
            this.SendSms2Async(senderId, phoneNo, carrier, message, isRequiredEnrollMsg, enrollMessage, applicationType, null);
        }
        
        /// <remarks/>
        public void SendSms2Async(string senderId, string phoneNo, string carrier, string message, bool isRequiredEnrollMsg, string enrollMessage, byte applicationType, object userState) {
            if ((this.SendSms2OperationCompleted == null)) {
                this.SendSms2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSms2OperationCompleted);
            }
            this.InvokeAsync("SendSms2", new object[] {
                        senderId,
                        phoneNo,
                        carrier,
                        message,
                        isRequiredEnrollMsg,
                        enrollMessage,
                        applicationType}, this.SendSms2OperationCompleted, userState);
        }
        
        private void OnSendSms2OperationCompleted(object arg) {
            if ((this.SendSms2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSms2Completed(this, new SendSms2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SendSms3", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfBoolean SendSms3(string senderId, string phoneNo, string carrier, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> minSendHour, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> maxSendHour, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out System.Nullable<long> messageId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out System.Nullable<long> enrollMessageId) {
            object[] results = this.Invoke("SendSms3", new object[] {
                        senderId,
                        phoneNo,
                        carrier,
                        message,
                        isRequiredEnrollMsg,
                        enrollMessage,
                        applicationType,
                        minSendHour,
                        maxSendHour});
            messageId = ((System.Nullable<long>)(results[1]));
            enrollMessageId = ((System.Nullable<long>)(results[2]));
            return ((ActionReturnOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void SendSms3Async(string senderId, string phoneNo, string carrier, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, System.Nullable<System.DateTime> minSendHour, System.Nullable<System.DateTime> maxSendHour) {
            this.SendSms3Async(senderId, phoneNo, carrier, message, isRequiredEnrollMsg, enrollMessage, applicationType, minSendHour, maxSendHour, null);
        }
        
        /// <remarks/>
        public void SendSms3Async(string senderId, string phoneNo, string carrier, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, System.Nullable<System.DateTime> minSendHour, System.Nullable<System.DateTime> maxSendHour, object userState) {
            if ((this.SendSms3OperationCompleted == null)) {
                this.SendSms3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSms3OperationCompleted);
            }
            this.InvokeAsync("SendSms3", new object[] {
                        senderId,
                        phoneNo,
                        carrier,
                        message,
                        isRequiredEnrollMsg,
                        enrollMessage,
                        applicationType,
                        minSendHour,
                        maxSendHour}, this.SendSms3OperationCompleted, userState);
        }
        
        private void OnSendSms3OperationCompleted(object arg) {
            if ((this.SendSms3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSms3Completed(this, new SendSms3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SaveNewPhoneNo2", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfBoolean SaveNewPhoneNo2(string senderId, string phoneNo, string carrier, string enrollMessage, byte applicationType, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out System.Nullable<long> messageId) {
            object[] results = this.Invoke("SaveNewPhoneNo2", new object[] {
                        senderId,
                        phoneNo,
                        carrier,
                        enrollMessage,
                        applicationType});
            messageId = ((System.Nullable<long>)(results[1]));
            return ((ActionReturnOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void SaveNewPhoneNo2Async(string senderId, string phoneNo, string carrier, string enrollMessage, byte applicationType) {
            this.SaveNewPhoneNo2Async(senderId, phoneNo, carrier, enrollMessage, applicationType, null);
        }
        
        /// <remarks/>
        public void SaveNewPhoneNo2Async(string senderId, string phoneNo, string carrier, string enrollMessage, byte applicationType, object userState) {
            if ((this.SaveNewPhoneNo2OperationCompleted == null)) {
                this.SaveNewPhoneNo2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveNewPhoneNo2OperationCompleted);
            }
            this.InvokeAsync("SaveNewPhoneNo2", new object[] {
                        senderId,
                        phoneNo,
                        carrier,
                        enrollMessage,
                        applicationType}, this.SaveNewPhoneNo2OperationCompleted, userState);
        }
        
        private void OnSaveNewPhoneNo2OperationCompleted(object arg) {
            if ((this.SaveNewPhoneNo2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveNewPhoneNo2Completed(this, new SaveNewPhoneNo2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SaveNewPhoneNo3", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfBoolean SaveNewPhoneNo3(string senderId, string phoneNo, string carrier, string enrollMessage, LSIDictAppType applicationType, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out System.Nullable<long> messageId) {
            object[] results = this.Invoke("SaveNewPhoneNo3", new object[] {
                        senderId,
                        phoneNo,
                        carrier,
                        enrollMessage,
                        applicationType});
            messageId = ((System.Nullable<long>)(results[1]));
            return ((ActionReturnOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void SaveNewPhoneNo3Async(string senderId, string phoneNo, string carrier, string enrollMessage, LSIDictAppType applicationType) {
            this.SaveNewPhoneNo3Async(senderId, phoneNo, carrier, enrollMessage, applicationType, null);
        }
        
        /// <remarks/>
        public void SaveNewPhoneNo3Async(string senderId, string phoneNo, string carrier, string enrollMessage, LSIDictAppType applicationType, object userState) {
            if ((this.SaveNewPhoneNo3OperationCompleted == null)) {
                this.SaveNewPhoneNo3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveNewPhoneNo3OperationCompleted);
            }
            this.InvokeAsync("SaveNewPhoneNo3", new object[] {
                        senderId,
                        phoneNo,
                        carrier,
                        enrollMessage,
                        applicationType}, this.SaveNewPhoneNo3OperationCompleted, userState);
        }
        
        private void OnSaveNewPhoneNo3OperationCompleted(object arg) {
            if ((this.SaveNewPhoneNo3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveNewPhoneNo3Completed(this, new SaveNewPhoneNo3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SendSmsWithBackup", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfSmsReturnObj SendSmsWithBackup(string senderId, string phoneNo, int countryCode, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, string subType, string internalId) {
            object[] results = this.Invoke("SendSmsWithBackup", new object[] {
                        senderId,
                        phoneNo,
                        countryCode,
                        message,
                        isRequiredEnrollMsg,
                        enrollMessage,
                        applicationType,
                        subType,
                        internalId});
            return ((ActionReturnOfSmsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsWithBackupAsync(string senderId, string phoneNo, int countryCode, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, string subType, string internalId) {
            this.SendSmsWithBackupAsync(senderId, phoneNo, countryCode, message, isRequiredEnrollMsg, enrollMessage, applicationType, subType, internalId, null);
        }
        
        /// <remarks/>
        public void SendSmsWithBackupAsync(string senderId, string phoneNo, int countryCode, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, string subType, string internalId, object userState) {
            if ((this.SendSmsWithBackupOperationCompleted == null)) {
                this.SendSmsWithBackupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsWithBackupOperationCompleted);
            }
            this.InvokeAsync("SendSmsWithBackup", new object[] {
                        senderId,
                        phoneNo,
                        countryCode,
                        message,
                        isRequiredEnrollMsg,
                        enrollMessage,
                        applicationType,
                        subType,
                        internalId}, this.SendSmsWithBackupOperationCompleted, userState);
        }
        
        private void OnSendSmsWithBackupOperationCompleted(object arg) {
            if ((this.SendSmsWithBackupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsWithBackupCompleted(this, new SendSmsWithBackupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SaveNewPhoneNoWithBackup", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfSmsReturnObj SaveNewPhoneNoWithBackup(string senderId, string phoneNo, int countryCode, string enrollMessage, LSIDictAppType applicationType, string subType, string internalId) {
            object[] results = this.Invoke("SaveNewPhoneNoWithBackup", new object[] {
                        senderId,
                        phoneNo,
                        countryCode,
                        enrollMessage,
                        applicationType,
                        subType,
                        internalId});
            return ((ActionReturnOfSmsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void SaveNewPhoneNoWithBackupAsync(string senderId, string phoneNo, int countryCode, string enrollMessage, LSIDictAppType applicationType, string subType, string internalId) {
            this.SaveNewPhoneNoWithBackupAsync(senderId, phoneNo, countryCode, enrollMessage, applicationType, subType, internalId, null);
        }
        
        /// <remarks/>
        public void SaveNewPhoneNoWithBackupAsync(string senderId, string phoneNo, int countryCode, string enrollMessage, LSIDictAppType applicationType, string subType, string internalId, object userState) {
            if ((this.SaveNewPhoneNoWithBackupOperationCompleted == null)) {
                this.SaveNewPhoneNoWithBackupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveNewPhoneNoWithBackupOperationCompleted);
            }
            this.InvokeAsync("SaveNewPhoneNoWithBackup", new object[] {
                        senderId,
                        phoneNo,
                        countryCode,
                        enrollMessage,
                        applicationType,
                        subType,
                        internalId}, this.SaveNewPhoneNoWithBackupOperationCompleted, userState);
        }
        
        private void OnSaveNewPhoneNoWithBackupOperationCompleted(object arg) {
            if ((this.SaveNewPhoneNoWithBackupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveNewPhoneNoWithBackupCompleted(this, new SaveNewPhoneNoWithBackupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/ClearPhoneNo", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfString ClearPhoneNo(int countryCode, string phoneNo) {
            object[] results = this.Invoke("ClearPhoneNo", new object[] {
                        countryCode,
                        phoneNo});
            return ((ActionReturnOfString)(results[0]));
        }
        
        /// <remarks/>
        public void ClearPhoneNoAsync(int countryCode, string phoneNo) {
            this.ClearPhoneNoAsync(countryCode, phoneNo, null);
        }
        
        /// <remarks/>
        public void ClearPhoneNoAsync(int countryCode, string phoneNo, object userState) {
            if ((this.ClearPhoneNoOperationCompleted == null)) {
                this.ClearPhoneNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearPhoneNoOperationCompleted);
            }
            this.InvokeAsync("ClearPhoneNo", new object[] {
                        countryCode,
                        phoneNo}, this.ClearPhoneNoOperationCompleted, userState);
        }
        
        private void OnClearPhoneNoOperationCompleted(object arg) {
            if ((this.ClearPhoneNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearPhoneNoCompleted(this, new ClearPhoneNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SaveNewPhoneNoWithBackup2", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfSmsReturnObj SaveNewPhoneNoWithBackup2(string senderId, string phoneNo, int countryCode, string enrollMessage, LSIDictAppType applicationType, string subType, string roamingSubType, string internalId) {
            object[] results = this.Invoke("SaveNewPhoneNoWithBackup2", new object[] {
                        senderId,
                        phoneNo,
                        countryCode,
                        enrollMessage,
                        applicationType,
                        subType,
                        roamingSubType,
                        internalId});
            return ((ActionReturnOfSmsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void SaveNewPhoneNoWithBackup2Async(string senderId, string phoneNo, int countryCode, string enrollMessage, LSIDictAppType applicationType, string subType, string roamingSubType, string internalId) {
            this.SaveNewPhoneNoWithBackup2Async(senderId, phoneNo, countryCode, enrollMessage, applicationType, subType, roamingSubType, internalId, null);
        }
        
        /// <remarks/>
        public void SaveNewPhoneNoWithBackup2Async(string senderId, string phoneNo, int countryCode, string enrollMessage, LSIDictAppType applicationType, string subType, string roamingSubType, string internalId, object userState) {
            if ((this.SaveNewPhoneNoWithBackup2OperationCompleted == null)) {
                this.SaveNewPhoneNoWithBackup2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveNewPhoneNoWithBackup2OperationCompleted);
            }
            this.InvokeAsync("SaveNewPhoneNoWithBackup2", new object[] {
                        senderId,
                        phoneNo,
                        countryCode,
                        enrollMessage,
                        applicationType,
                        subType,
                        roamingSubType,
                        internalId}, this.SaveNewPhoneNoWithBackup2OperationCompleted, userState);
        }
        
        private void OnSaveNewPhoneNoWithBackup2OperationCompleted(object arg) {
            if ((this.SaveNewPhoneNoWithBackup2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveNewPhoneNoWithBackup2Completed(this, new SaveNewPhoneNoWithBackup2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SendSmsWithBackup2", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfSmsReturnObj SendSmsWithBackup2(string senderId, string phoneNo, int countryCode, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, string subType, string roamingSubType, string internalId, bool createNewConversation, string tariff) {
            object[] results = this.Invoke("SendSmsWithBackup2", new object[] {
                        senderId,
                        phoneNo,
                        countryCode,
                        message,
                        isRequiredEnrollMsg,
                        enrollMessage,
                        applicationType,
                        subType,
                        roamingSubType,
                        internalId,
                        createNewConversation,
                        tariff});
            return ((ActionReturnOfSmsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsWithBackup2Async(string senderId, string phoneNo, int countryCode, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, string subType, string roamingSubType, string internalId, bool createNewConversation, string tariff) {
            this.SendSmsWithBackup2Async(senderId, phoneNo, countryCode, message, isRequiredEnrollMsg, enrollMessage, applicationType, subType, roamingSubType, internalId, createNewConversation, tariff, null);
        }
        
        /// <remarks/>
        public void SendSmsWithBackup2Async(string senderId, string phoneNo, int countryCode, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, string subType, string roamingSubType, string internalId, bool createNewConversation, string tariff, object userState) {
            if ((this.SendSmsWithBackup2OperationCompleted == null)) {
                this.SendSmsWithBackup2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsWithBackup2OperationCompleted);
            }
            this.InvokeAsync("SendSmsWithBackup2", new object[] {
                        senderId,
                        phoneNo,
                        countryCode,
                        message,
                        isRequiredEnrollMsg,
                        enrollMessage,
                        applicationType,
                        subType,
                        roamingSubType,
                        internalId,
                        createNewConversation,
                        tariff}, this.SendSmsWithBackup2OperationCompleted, userState);
        }
        
        private void OnSendSmsWithBackup2OperationCompleted(object arg) {
            if ((this.SendSmsWithBackup2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsWithBackup2Completed(this, new SendSmsWithBackup2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/SendSmsWithBackupParams", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfSmsReturnObj SendSmsWithBackupParams(string senderId, string phoneNo, int countryCode, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, string subType, string roamingSubType, string internalId, bool createNewConversation, string tariff, Param[] parameters) {
            object[] results = this.Invoke("SendSmsWithBackupParams", new object[] {
                        senderId,
                        phoneNo,
                        countryCode,
                        message,
                        isRequiredEnrollMsg,
                        enrollMessage,
                        applicationType,
                        subType,
                        roamingSubType,
                        internalId,
                        createNewConversation,
                        tariff,
                        parameters});
            return ((ActionReturnOfSmsReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsWithBackupParamsAsync(string senderId, string phoneNo, int countryCode, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, string subType, string roamingSubType, string internalId, bool createNewConversation, string tariff, Param[] parameters) {
            this.SendSmsWithBackupParamsAsync(senderId, phoneNo, countryCode, message, isRequiredEnrollMsg, enrollMessage, applicationType, subType, roamingSubType, internalId, createNewConversation, tariff, parameters, null);
        }
        
        /// <remarks/>
        public void SendSmsWithBackupParamsAsync(string senderId, string phoneNo, int countryCode, string message, bool isRequiredEnrollMsg, string enrollMessage, LSIDictAppType applicationType, string subType, string roamingSubType, string internalId, bool createNewConversation, string tariff, Param[] parameters, object userState) {
            if ((this.SendSmsWithBackupParamsOperationCompleted == null)) {
                this.SendSmsWithBackupParamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsWithBackupParamsOperationCompleted);
            }
            this.InvokeAsync("SendSmsWithBackupParams", new object[] {
                        senderId,
                        phoneNo,
                        countryCode,
                        message,
                        isRequiredEnrollMsg,
                        enrollMessage,
                        applicationType,
                        subType,
                        roamingSubType,
                        internalId,
                        createNewConversation,
                        tariff,
                        parameters}, this.SendSmsWithBackupParamsOperationCompleted, userState);
        }
        
        private void OnSendSmsWithBackupParamsOperationCompleted(object arg) {
            if ((this.SendSmsWithBackupParamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsWithBackupParamsCompleted(this, new SendSmsWithBackupParamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/GetSmsList", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfArrayOfString GetSmsList(LSIDictAppType[] applicationList, System.DateTime utcLastModify) {
            object[] results = this.Invoke("GetSmsList", new object[] {
                        applicationList,
                        utcLastModify});
            return ((ActionReturnOfArrayOfString)(results[0]));
        }
        
        /// <remarks/>
        public void GetSmsListAsync(LSIDictAppType[] applicationList, System.DateTime utcLastModify) {
            this.GetSmsListAsync(applicationList, utcLastModify, null);
        }
        
        /// <remarks/>
        public void GetSmsListAsync(LSIDictAppType[] applicationList, System.DateTime utcLastModify, object userState) {
            if ((this.GetSmsListOperationCompleted == null)) {
                this.GetSmsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSmsListOperationCompleted);
            }
            this.InvokeAsync("GetSmsList", new object[] {
                        applicationList,
                        utcLastModify}, this.GetSmsListOperationCompleted, userState);
        }
        
        private void OnGetSmsListOperationCompleted(object arg) {
            if ((this.GetSmsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSmsListCompleted(this, new GetSmsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/IsPermium", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfBoolean IsPermium(string phoneNo, string countryCode) {
            object[] results = this.Invoke("IsPermium", new object[] {
                        phoneNo,
                        countryCode});
            return ((ActionReturnOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void IsPermiumAsync(string phoneNo, string countryCode) {
            this.IsPermiumAsync(phoneNo, countryCode, null);
        }
        
        /// <remarks/>
        public void IsPermiumAsync(string phoneNo, string countryCode, object userState) {
            if ((this.IsPermiumOperationCompleted == null)) {
                this.IsPermiumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsPermiumOperationCompleted);
            }
            this.InvokeAsync("IsPermium", new object[] {
                        phoneNo,
                        countryCode}, this.IsPermiumOperationCompleted, userState);
        }
        
        private void OnIsPermiumOperationCompleted(object arg) {
            if ((this.IsPermiumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsPermiumCompleted(this, new IsPermiumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/IsPermiumOperator", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfIsPremiumReturnObj IsPermiumOperator(string phoneNo, string countryCode) {
            object[] results = this.Invoke("IsPermiumOperator", new object[] {
                        phoneNo,
                        countryCode});
            return ((ActionReturnOfIsPremiumReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void IsPermiumOperatorAsync(string phoneNo, string countryCode) {
            this.IsPermiumOperatorAsync(phoneNo, countryCode, null);
        }
        
        /// <remarks/>
        public void IsPermiumOperatorAsync(string phoneNo, string countryCode, object userState) {
            if ((this.IsPermiumOperatorOperationCompleted == null)) {
                this.IsPermiumOperatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsPermiumOperatorOperationCompleted);
            }
            this.InvokeAsync("IsPermiumOperator", new object[] {
                        phoneNo,
                        countryCode}, this.IsPermiumOperatorOperationCompleted, userState);
        }
        
        private void OnIsPermiumOperatorOperationCompleted(object arg) {
            if ((this.IsPermiumOperatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsPermiumOperatorCompleted(this, new IsPermiumOperatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://lsi.software.pl/WSMailer/IsPermiumOperator2", RequestNamespace="http://lsi.software.pl/WSMailer/", ResponseNamespace="http://lsi.software.pl/WSMailer/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActionReturnOfIsPremiumReturnObj IsPermiumOperator2(string phoneNo, string countryCode, LSIDictAppType applicationType) {
            object[] results = this.Invoke("IsPermiumOperator2", new object[] {
                        phoneNo,
                        countryCode,
                        applicationType});
            return ((ActionReturnOfIsPremiumReturnObj)(results[0]));
        }
        
        /// <remarks/>
        public void IsPermiumOperator2Async(string phoneNo, string countryCode, LSIDictAppType applicationType) {
            this.IsPermiumOperator2Async(phoneNo, countryCode, applicationType, null);
        }
        
        /// <remarks/>
        public void IsPermiumOperator2Async(string phoneNo, string countryCode, LSIDictAppType applicationType, object userState) {
            if ((this.IsPermiumOperator2OperationCompleted == null)) {
                this.IsPermiumOperator2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsPermiumOperator2OperationCompleted);
            }
            this.InvokeAsync("IsPermiumOperator2", new object[] {
                        phoneNo,
                        countryCode,
                        applicationType}, this.IsPermiumOperator2OperationCompleted, userState);
        }
        
        private void OnIsPermiumOperator2OperationCompleted(object arg) {
            if ((this.IsPermiumOperator2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsPermiumOperator2Completed(this, new IsPermiumOperator2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class ClientSendMailTemplate {
        
        private string toAddressField;
        
        private string toPersonField;
        
        private string subjectField;
        
        private string mailTemplateIdField;
        
        private string clientMailIdField;
        
        private Replacement[] mailReplacementField;
        
        /// <remarks/>
        public string ToAddress {
            get {
                return this.toAddressField;
            }
            set {
                this.toAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ToPerson {
            get {
                return this.toPersonField;
            }
            set {
                this.toPersonField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string MailTemplateId {
            get {
                return this.mailTemplateIdField;
            }
            set {
                this.mailTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailId {
            get {
                return this.clientMailIdField;
            }
            set {
                this.clientMailIdField = value;
            }
        }
        
        /// <remarks/>
        public Replacement[] MailReplacement {
            get {
                return this.mailReplacementField;
            }
            set {
                this.mailReplacementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class Replacement {
        
        private string currentStringField;
        
        private string newStringField;
        
        /// <remarks/>
        public string CurrentString {
            get {
                return this.currentStringField;
            }
            set {
                this.currentStringField = value;
            }
        }
        
        /// <remarks/>
        public string NewString {
            get {
                return this.newStringField;
            }
            set {
                this.newStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class IsPremiumReturnObj {
        
        private string operatorIdField;
        
        private bool isPermiumField;
        
        /// <remarks/>
        public string OperatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsPermium {
            get {
                return this.isPermiumField;
            }
            set {
                this.isPermiumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class ActionReturnOfIsPremiumReturnObj {
        
        private IsPremiumReturnObj addDataField;
        
        private ActionReturnStatusEnumOfIsPremiumReturnObj statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public IsPremiumReturnObj AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfIsPremiumReturnObj Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public enum ActionReturnStatusEnumOfIsPremiumReturnObj {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class ActionReturnOfArrayOfString {
        
        private string[] addDataField;
        
        private ActionReturnStatusEnumOfArrayOfString statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string[] AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfArrayOfString Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public enum ActionReturnStatusEnumOfArrayOfString {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class Param {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class ActionReturnOfString {
        
        private string addDataField;
        
        private ActionReturnStatusEnumOfString statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfString Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public enum ActionReturnStatusEnumOfString {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class SmsReturnObj {
        
        private System.Nullable<bool> roamingCarrierUsedField;
        
        private System.Nullable<long> msgIDField;
        
        private System.Nullable<long> enrollMsgIDField;
        
        private SmsReturnValues statusField;
        
        private string carrierField;
        
        private string clearPhoneNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> RoamingCarrierUsed {
            get {
                return this.roamingCarrierUsedField;
            }
            set {
                this.roamingCarrierUsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> EnrollMsgID {
            get {
                return this.enrollMsgIDField;
            }
            set {
                this.enrollMsgIDField = value;
            }
        }
        
        /// <remarks/>
        public SmsReturnValues Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        public string ClearPhoneNo {
            get {
                return this.clearPhoneNoField;
            }
            set {
                this.clearPhoneNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public enum SmsReturnValues {
        
        /// <remarks/>
        OptOut,
        
        /// <remarks/>
        SendSuccessfuly,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class ActionReturnOfSmsReturnObj {
        
        private SmsReturnObj addDataField;
        
        private ActionReturnStatusEnumOfSmsReturnObj statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public SmsReturnObj AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfSmsReturnObj Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public enum ActionReturnStatusEnumOfSmsReturnObj {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class ActionReturnOfBoolean {
        
        private bool addDataField;
        
        private ActionReturnStatusEnumOfBoolean statusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public bool AddData {
            get {
                return this.addDataField;
            }
            set {
                this.addDataField = value;
            }
        }
        
        /// <remarks/>
        public ActionReturnStatusEnumOfBoolean Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public enum ActionReturnStatusEnumOfBoolean {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public partial class ClientMailSendReturn {
        
        private System.Nullable<long> mailIDField;
        
        private StatusMailReturn sendStatusField;
        
        private string errorSendMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> MailID {
            get {
                return this.mailIDField;
            }
            set {
                this.mailIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusMailReturn SendStatus {
            get {
                return this.sendStatusField;
            }
            set {
                this.sendStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorSendMsg {
            get {
                return this.errorSendMsgField;
            }
            set {
                this.errorSendMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public enum StatusMailReturn {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        SendOk,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lsi.software.pl/WSMailer/")]
    public enum LSIDictAppType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        PP,
        
        /// <remarks/>
        NP,
        
        /// <remarks/>
        CAS,
        
        /// <remarks/>
        Survey,
        
        /// <remarks/>
        Valet,
        
        /// <remarks/>
        WaiterLocator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendMailTemplateCompletedEventHandler(object sender, SendMailTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMailTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMailTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientMailSendReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientMailSendReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendSmsCompletedEventHandler(object sender, SendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveNewPhoneNoCompletedEventHandler(object sender, SaveNewPhoneNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveNewPhoneNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveNewPhoneNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void RemovePhoneNumberCompletedEventHandler(object sender, RemovePhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemovePhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemovePhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void IsCallNeededCompletedEventHandler(object sender, IsCallNeededCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCallNeededCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsCallNeededCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendSms2CompletedEventHandler(object sender, SendSms2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSms2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSms2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfBoolean)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Nullable<long> messageId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<long>)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public System.Nullable<long> enrollMessageId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<long>)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendSms3CompletedEventHandler(object sender, SendSms3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSms3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSms3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfBoolean)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Nullable<long> messageId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<long>)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public System.Nullable<long> enrollMessageId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<long>)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveNewPhoneNo2CompletedEventHandler(object sender, SaveNewPhoneNo2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveNewPhoneNo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveNewPhoneNo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfBoolean)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Nullable<long> messageId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<long>)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveNewPhoneNo3CompletedEventHandler(object sender, SaveNewPhoneNo3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveNewPhoneNo3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveNewPhoneNo3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfBoolean)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Nullable<long> messageId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<long>)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendSmsWithBackupCompletedEventHandler(object sender, SendSmsWithBackupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsWithBackupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsWithBackupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfSmsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfSmsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveNewPhoneNoWithBackupCompletedEventHandler(object sender, SaveNewPhoneNoWithBackupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveNewPhoneNoWithBackupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveNewPhoneNoWithBackupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfSmsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfSmsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void ClearPhoneNoCompletedEventHandler(object sender, ClearPhoneNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClearPhoneNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClearPhoneNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfString)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SaveNewPhoneNoWithBackup2CompletedEventHandler(object sender, SaveNewPhoneNoWithBackup2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveNewPhoneNoWithBackup2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveNewPhoneNoWithBackup2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfSmsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfSmsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendSmsWithBackup2CompletedEventHandler(object sender, SendSmsWithBackup2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsWithBackup2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsWithBackup2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfSmsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfSmsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendSmsWithBackupParamsCompletedEventHandler(object sender, SendSmsWithBackupParamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsWithBackupParamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsWithBackupParamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfSmsReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfSmsReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetSmsListCompletedEventHandler(object sender, GetSmsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSmsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSmsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfArrayOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfArrayOfString)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void IsPermiumCompletedEventHandler(object sender, IsPermiumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPermiumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsPermiumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void IsPermiumOperatorCompletedEventHandler(object sender, IsPermiumOperatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPermiumOperatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsPermiumOperatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfIsPremiumReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfIsPremiumReturnObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void IsPermiumOperator2CompletedEventHandler(object sender, IsPermiumOperator2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPermiumOperator2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsPermiumOperator2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionReturnOfIsPremiumReturnObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionReturnOfIsPremiumReturnObj)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591