using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.ComponentModel;

// generated by MyGeneration / DtoTemplate 
// on 2011-10-17 11:12:50

namespace ConApp_VS2k8.Dto
{
    /// <summary>
    /// Dto for WLTableMessages table 
    /// </summary>
    [Serializable]
    public class WLTableMessagesDto : ICloneable, IEquatable<WLTableMessagesDto>, IEditableObject
    {
        private bool isEdit;
        private bool isModified;
		
        private readonly WLTableMessagesDto oldValues;
        
		
        /// <summary>
        /// Gets the dto with old values
        /// </summary>
        /// <value>The old values.</value>
        public WLTableMessagesDto OldValues
        {
            get { return oldValues; }
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="WLTableMessagesDto"/> class.
        /// Used internally to distinguish between current and old values
        /// </summary>
        /// <param name="isOldValue">if set to <c>true</c> the dto represents the 
        /// inner instance with old values.</param>
        private WLTableMessagesDto(bool isOldValue)
        {
            if (! isOldValue)
                oldValues = new WLTableMessagesDto(true);
        }

        /// <summary>
        /// Gets a value indicating whether this instance is modified
        /// since last DB read or creation
        /// </summary>
        /// <value>
        /// 	<c>true</c> if this instance is modified; otherwise, <c>false</c>.
        /// </value>
        public bool IsModified
        {
            get { return isModified; }
        }


        private bool isNew = true;
        /// <summary>
        /// Gets a value indicating whether this instance is new.
        /// </summary>
        /// <value><c>true</c> if this instance is new; otherwise, <c>false</c>.</value>
        public bool IsNew
        {
            get { return isNew;}
        }

        /// <summary>
        /// Sets the is new.
        /// </summary>
        /// <param name="isNew">if set to <c>true</c> [is new].</param>
        public void SetIsNew (bool isNew)
        {
            this.isNew = isNew; 
        }
		
        /// <summary>
        /// Sets the is modified flag.
        /// </summary>
        /// <param name="isModified">new value of isModified flag.</param>
        public void SetIsModified(bool isModified)
        {
            this.isModified = isModified;
        }
	
	
        private long wLTableId;

        /// <summary> 
        /// Gets or sets the WLTableId.
        /// </summary>
        /// <value> WLTableId</value>
        [XmlAttribute]		
        public long WLTableId
        {
            [DebuggerStepThrough]
            get { return this.wLTableId; }
            [DebuggerStepThrough]
            set
            {
                if (!value.Equals(this.wLTableId))
                {
                    this.isModified = true;
                    this.wLTableId = value;
                }
		
            }
        }
		
	
        private string beachButlerMessage;

        /// <summary> 
        /// Gets or sets the BeachButlerMessage.
        /// </summary>
        /// <value> BeachButlerMessage</value>
				
        public string BeachButlerMessage
        {
            [DebuggerStepThrough]
            get { return this.beachButlerMessage; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.beachButlerMessage != null)
                     || (value != null && !value.Equals(this.beachButlerMessage)))
                {
                    this.isModified = true; 
                    this.beachButlerMessage = value;
                }
		
            }
        }
		
	
        private string tableGenieLeftButtonMessage;

        /// <summary> 
        /// Gets or sets the TableGenieLeftButtonMessage.
        /// </summary>
        /// <value> TableGenieLeftButtonMessage</value>
				
        public string TableGenieLeftButtonMessage
        {
            [DebuggerStepThrough]
            get { return this.tableGenieLeftButtonMessage; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.tableGenieLeftButtonMessage != null)
                     || (value != null && !value.Equals(this.tableGenieLeftButtonMessage)))
                {
                    this.isModified = true; 
                    this.tableGenieLeftButtonMessage = value;
                }
		
            }
        }
		
	
        private string tableGenieMiddleButtonMessage;

        /// <summary> 
        /// Gets or sets the TableGenieMiddleButtonMessage.
        /// </summary>
        /// <value> TableGenieMiddleButtonMessage</value>
				
        public string TableGenieMiddleButtonMessage
        {
            [DebuggerStepThrough]
            get { return this.tableGenieMiddleButtonMessage; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.tableGenieMiddleButtonMessage != null)
                     || (value != null && !value.Equals(this.tableGenieMiddleButtonMessage)))
                {
                    this.isModified = true; 
                    this.tableGenieMiddleButtonMessage = value;
                }
		
            }
        }
		
	
        private string tableGenieRightButtonMessage;

        /// <summary> 
        /// Gets or sets the TableGenieRightButtonMessage.
        /// </summary>
        /// <value> TableGenieRightButtonMessage</value>
				
        public string TableGenieRightButtonMessage
        {
            [DebuggerStepThrough]
            get { return this.tableGenieRightButtonMessage; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.tableGenieRightButtonMessage != null)
                     || (value != null && !value.Equals(this.tableGenieRightButtonMessage)))
                {
                    this.isModified = true; 
                    this.tableGenieRightButtonMessage = value;
                }
		
            }
        }
		
	
        private int wLDictChangeStatusId;

        /// <summary> 
        /// Gets or sets the WLDictChangeStatusId.
        /// </summary>
        /// <value> WLDictChangeStatusId</value>
        [XmlAttribute]		
        public int WLDictChangeStatusId
        {
            [DebuggerStepThrough]
            get { return this.wLDictChangeStatusId; }
            [DebuggerStepThrough]
            set
            {
                if (!value.Equals(this.wLDictChangeStatusId))
                {
                    this.isModified = true;
                    this.wLDictChangeStatusId = value;
                }
		
            }
        }
		
	
        ///<summary>
        ///Creates a new object that is a copy of the current instance.
        ///</summary>
        ///<returns>A new object that is a copy of this instance.</returns>
        public object Clone()
        {
            return new WLTableMessagesDto(this.WLTableId,
                                          this.BeachButlerMessage,
                                          this.TableGenieLeftButtonMessage,
                                          this.TableGenieMiddleButtonMessage,
                                          this.TableGenieRightButtonMessage,
                                          this.WLDictChangeStatusId
                );
        }

        ///<summary>
        ///Indicates whether the current object is equal to another object of the same type.
        ///</summary>
        ///<returns>true if the current object is equal to the other parameter; otherwise, false.</returns>
        ///<param name="other">An object to compare with this object.</param>
        public bool Equals(WLTableMessagesDto other)
        {
            if (other == null)
                return false;
				
            return this.wLTableId.Equals (other.wLTableId)
                   && ( (this.beachButlerMessage == null && other.beachButlerMessage == null ) || (this.beachButlerMessage != null && this.beachButlerMessage.Equals (other.beachButlerMessage)))
                   && ( (this.tableGenieLeftButtonMessage == null && other.tableGenieLeftButtonMessage == null ) || (this.tableGenieLeftButtonMessage != null && this.tableGenieLeftButtonMessage.Equals (other.tableGenieLeftButtonMessage)))
                   && ( (this.tableGenieMiddleButtonMessage == null && other.tableGenieMiddleButtonMessage == null ) || (this.tableGenieMiddleButtonMessage != null && this.tableGenieMiddleButtonMessage.Equals (other.tableGenieMiddleButtonMessage)))
                   && ( (this.tableGenieRightButtonMessage == null && other.tableGenieRightButtonMessage == null ) || (this.tableGenieRightButtonMessage != null && this.tableGenieRightButtonMessage.Equals (other.tableGenieRightButtonMessage)))
                   && this.wLDictChangeStatusId.Equals (other.wLDictChangeStatusId)
                ;
        }
		
        /// <summary>
        /// Copies the property values from another instance
        /// </summary>
        /// <param name="source">The source instance.</param>
        public void CopyProperties(WLTableMessagesDto source)
        {
            this.WLTableId = source.WLTableId;
            this.BeachButlerMessage = source.BeachButlerMessage;
            this.TableGenieLeftButtonMessage = source.TableGenieLeftButtonMessage;
            this.TableGenieMiddleButtonMessage = source.TableGenieMiddleButtonMessage;
            this.TableGenieRightButtonMessage = source.TableGenieRightButtonMessage;
            this.WLDictChangeStatusId = source.WLDictChangeStatusId;

        }



        /// <summary>
        /// Initializes a new instance of the <see cref="WLTableMessagesDto"/> class.
        /// All values can be provided
        /// </summary>
        ///<param name="wLTableId">WLTableMessages.wLTableId</param>
        ///<param name="beachButlerMessage">WLTableMessages.beachButlerMessage</param>
        ///<param name="tableGenieLeftButtonMessage">WLTableMessages.tableGenieLeftButtonMessage</param>
        ///<param name="tableGenieMiddleButtonMessage">WLTableMessages.tableGenieMiddleButtonMessage</param>
        ///<param name="tableGenieRightButtonMessage">WLTableMessages.tableGenieRightButtonMessage</param>
        ///<param name="wLDictChangeStatusId">WLTableMessages.wLDictChangeStatusId</param>

        public WLTableMessagesDto(long wLTableId, string beachButlerMessage, string tableGenieLeftButtonMessage, string tableGenieMiddleButtonMessage, string tableGenieRightButtonMessage, int wLDictChangeStatusId) : this(false)
        {
            this.wLTableId = wLTableId;
            this.beachButlerMessage = beachButlerMessage;
            this.tableGenieLeftButtonMessage = tableGenieLeftButtonMessage;
            this.tableGenieMiddleButtonMessage = tableGenieMiddleButtonMessage;
            this.tableGenieRightButtonMessage = tableGenieRightButtonMessage;
            this.wLDictChangeStatusId = wLDictChangeStatusId;
			
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="WLTableMessagesDto"/> class;
        /// creates new (empty) DTO
        /// Not null values can be provided
        /// </summary>
        public WLTableMessagesDto(long wLTableId, int wLDictChangeStatusId) : this(false)
        {
            this.wLTableId = wLTableId;
            this.wLDictChangeStatusId = wLDictChangeStatusId;

        }

		
        /// <summary>
        /// Initializes a new instance of the <see cref="WLTableMessagesDto"/> class;
        /// creates new (empty) DTO
        /// Parameterless cstr - avoid using it if no nocessary!
        /// </summary>
        public WLTableMessagesDto() : this(false)
        {
        }
		
        ///<summary>
        ///Begins an edit on an object.
        ///</summary>
        ///
        public void BeginEdit()
        {
            if (!isEdit)
            {
                isEdit = true;
                this.OldValues.CopyProperties(this);
            }
        }

        ///<summary>
        ///Pushes changes since the last <see cref="M:System.ComponentModel.IEditableObject.BeginEdit"></see> 
        /// or <see cref="M:System.ComponentModel.IBindingList.AddNew"></see> call into the underlying object.
        ///</summary>
        public void EndEdit()
        {
            isEdit = false;
        }

        ///<summary>
        ///Discards changes since the last <see cref="M:System.ComponentModel.IEditableObject.BeginEdit"></see> call.
        ///</summary>
        public void CancelEdit()
        {
            if (isEdit)
            {
                this.CopyProperties(this.OldValues);
                isEdit = false;
            }
        }
    }

    /// <summary>
    /// List of WLTableMessagesDto
    /// </summary>
    [Serializable]
    public class WLTableMessagesCollection : BindingList<WLTableMessagesDto>
    {
	
        /// <summary>
        /// Finds dto in collection by specified key values; null if no object matching
        /// </summary>
        /// <param name="wLTableId">The wLTableId.</param>
        /// <returns>found dto or null if not found</returns>
        public WLTableMessagesDto FindByWLTableId (long wLTableId)
        {
            foreach (WLTableMessagesDto dto in this)
                if (dto.WLTableId == wLTableId)
                    return dto;
            return null; 
        }
	
    }

    /// <summary>
    /// Filter for WLTableMessagesDto
    /// </summary>
    [Serializable]
    public class WLTableMessagesFilter
    {

        private long? wLTableId;

        /// <summary> 
        /// Gets or sets the WLTableId.
        /// </summary>
        /// <value> WLTableId</value>
        [XmlAttribute]		
        public long? WLTableId
        {
            [DebuggerStepThrough]
            get { return this.wLTableId; }
            [DebuggerStepThrough]
            set { this.wLTableId = value; }
        }
	
        /// <summary> 
        /// Sets the WLTableId value.
        /// </summary>
        /// <value> WLTableId</value>
        public WLTableMessagesFilter SetWLTableId (long? wLTableId)
        {
            this.wLTableId = wLTableId; 
            return this; 
        }
	
        private long? wLTableId_RngLow;

        /// <summary> 
        /// Gets or sets the WLTableId_RngLow.
        /// </summary>
        /// <value> WLTableId_RngLow</value>
				
        public long? WLTableId_RngLow
        {
            [DebuggerStepThrough]
            get { return this.wLTableId_RngLow; }
            [DebuggerStepThrough]
            set { this.wLTableId_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the WLTableId_RngLow value.
        /// </summary>
        /// <value> WLTableId_RngLow</value>
        public WLTableMessagesFilter SetWLTableId_RngLow (long? wLTableId_RngLow)
        {
            this.wLTableId_RngLow = wLTableId_RngLow; 
            return this; 
        }
	
        private long? wLTableId_RngHigh;

        /// <summary> 
        /// Gets or sets the WLTableId_RngHigh.
        /// </summary>
        /// <value> WLTableId_RngHigh</value>
				
        public long? WLTableId_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.wLTableId_RngHigh; }
            [DebuggerStepThrough]
            set { this.wLTableId_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the WLTableId_RngHigh value.
        /// </summary>
        /// <value> WLTableId_RngHigh</value>
        public WLTableMessagesFilter SetWLTableId_RngHigh (long? wLTableId_RngHigh)
        {
            this.wLTableId_RngHigh = wLTableId_RngHigh; 
            return this; 
        }
	
        private string beachButlerMessage;

        /// <summary> 
        /// Gets or sets the BeachButlerMessage.
        /// </summary>
        /// <value> BeachButlerMessage</value>
				
        public string BeachButlerMessage
        {
            [DebuggerStepThrough]
            get { return this.beachButlerMessage; }
            [DebuggerStepThrough]
            set { this.beachButlerMessage = value; }
        }
	
        /// <summary> 
        /// Sets the BeachButlerMessage value.
        /// </summary>
        /// <value> BeachButlerMessage</value>
        public WLTableMessagesFilter SetBeachButlerMessage (string beachButlerMessage)
        {
            this.beachButlerMessage = beachButlerMessage; 
            return this; 
        }
	
        private string beachButlerMessage_LikeComp;

        /// <summary> 
        /// Gets or sets the BeachButlerMessage_LikeComp.
        /// </summary>
        /// <value> BeachButlerMessage_LikeComp</value>
				
        public string BeachButlerMessage_LikeComp
        {
            [DebuggerStepThrough]
            get { return this.beachButlerMessage_LikeComp; }
            [DebuggerStepThrough]
            set { this.beachButlerMessage_LikeComp = value; }
        }
	
        /// <summary> 
        /// Sets the BeachButlerMessage_LikeComp value.
        /// </summary>
        /// <value> BeachButlerMessage_LikeComp</value>
        public WLTableMessagesFilter SetBeachButlerMessage_LikeComp (string beachButlerMessage_LikeComp)
        {
            this.beachButlerMessage_LikeComp = beachButlerMessage_LikeComp; 
            return this; 
        }
	
        private string tableGenieLeftButtonMessage;

        /// <summary> 
        /// Gets or sets the TableGenieLeftButtonMessage.
        /// </summary>
        /// <value> TableGenieLeftButtonMessage</value>
				
        public string TableGenieLeftButtonMessage
        {
            [DebuggerStepThrough]
            get { return this.tableGenieLeftButtonMessage; }
            [DebuggerStepThrough]
            set { this.tableGenieLeftButtonMessage = value; }
        }
	
        /// <summary> 
        /// Sets the TableGenieLeftButtonMessage value.
        /// </summary>
        /// <value> TableGenieLeftButtonMessage</value>
        public WLTableMessagesFilter SetTableGenieLeftButtonMessage (string tableGenieLeftButtonMessage)
        {
            this.tableGenieLeftButtonMessage = tableGenieLeftButtonMessage; 
            return this; 
        }
	
        private string tableGenieLeftButtonMessage_LikeComp;

        /// <summary> 
        /// Gets or sets the TableGenieLeftButtonMessage_LikeComp.
        /// </summary>
        /// <value> TableGenieLeftButtonMessage_LikeComp</value>
				
        public string TableGenieLeftButtonMessage_LikeComp
        {
            [DebuggerStepThrough]
            get { return this.tableGenieLeftButtonMessage_LikeComp; }
            [DebuggerStepThrough]
            set { this.tableGenieLeftButtonMessage_LikeComp = value; }
        }
	
        /// <summary> 
        /// Sets the TableGenieLeftButtonMessage_LikeComp value.
        /// </summary>
        /// <value> TableGenieLeftButtonMessage_LikeComp</value>
        public WLTableMessagesFilter SetTableGenieLeftButtonMessage_LikeComp (string tableGenieLeftButtonMessage_LikeComp)
        {
            this.tableGenieLeftButtonMessage_LikeComp = tableGenieLeftButtonMessage_LikeComp; 
            return this; 
        }
	
        private string tableGenieMiddleButtonMessage;

        /// <summary> 
        /// Gets or sets the TableGenieMiddleButtonMessage.
        /// </summary>
        /// <value> TableGenieMiddleButtonMessage</value>
				
        public string TableGenieMiddleButtonMessage
        {
            [DebuggerStepThrough]
            get { return this.tableGenieMiddleButtonMessage; }
            [DebuggerStepThrough]
            set { this.tableGenieMiddleButtonMessage = value; }
        }
	
        /// <summary> 
        /// Sets the TableGenieMiddleButtonMessage value.
        /// </summary>
        /// <value> TableGenieMiddleButtonMessage</value>
        public WLTableMessagesFilter SetTableGenieMiddleButtonMessage (string tableGenieMiddleButtonMessage)
        {
            this.tableGenieMiddleButtonMessage = tableGenieMiddleButtonMessage; 
            return this; 
        }
	
        private string tableGenieMiddleButtonMessage_LikeComp;

        /// <summary> 
        /// Gets or sets the TableGenieMiddleButtonMessage_LikeComp.
        /// </summary>
        /// <value> TableGenieMiddleButtonMessage_LikeComp</value>
				
        public string TableGenieMiddleButtonMessage_LikeComp
        {
            [DebuggerStepThrough]
            get { return this.tableGenieMiddleButtonMessage_LikeComp; }
            [DebuggerStepThrough]
            set { this.tableGenieMiddleButtonMessage_LikeComp = value; }
        }
	
        /// <summary> 
        /// Sets the TableGenieMiddleButtonMessage_LikeComp value.
        /// </summary>
        /// <value> TableGenieMiddleButtonMessage_LikeComp</value>
        public WLTableMessagesFilter SetTableGenieMiddleButtonMessage_LikeComp (string tableGenieMiddleButtonMessage_LikeComp)
        {
            this.tableGenieMiddleButtonMessage_LikeComp = tableGenieMiddleButtonMessage_LikeComp; 
            return this; 
        }
	
        private string tableGenieRightButtonMessage;

        /// <summary> 
        /// Gets or sets the TableGenieRightButtonMessage.
        /// </summary>
        /// <value> TableGenieRightButtonMessage</value>
				
        public string TableGenieRightButtonMessage
        {
            [DebuggerStepThrough]
            get { return this.tableGenieRightButtonMessage; }
            [DebuggerStepThrough]
            set { this.tableGenieRightButtonMessage = value; }
        }
	
        /// <summary> 
        /// Sets the TableGenieRightButtonMessage value.
        /// </summary>
        /// <value> TableGenieRightButtonMessage</value>
        public WLTableMessagesFilter SetTableGenieRightButtonMessage (string tableGenieRightButtonMessage)
        {
            this.tableGenieRightButtonMessage = tableGenieRightButtonMessage; 
            return this; 
        }
	
        private string tableGenieRightButtonMessage_LikeComp;

        /// <summary> 
        /// Gets or sets the TableGenieRightButtonMessage_LikeComp.
        /// </summary>
        /// <value> TableGenieRightButtonMessage_LikeComp</value>
				
        public string TableGenieRightButtonMessage_LikeComp
        {
            [DebuggerStepThrough]
            get { return this.tableGenieRightButtonMessage_LikeComp; }
            [DebuggerStepThrough]
            set { this.tableGenieRightButtonMessage_LikeComp = value; }
        }
	
        /// <summary> 
        /// Sets the TableGenieRightButtonMessage_LikeComp value.
        /// </summary>
        /// <value> TableGenieRightButtonMessage_LikeComp</value>
        public WLTableMessagesFilter SetTableGenieRightButtonMessage_LikeComp (string tableGenieRightButtonMessage_LikeComp)
        {
            this.tableGenieRightButtonMessage_LikeComp = tableGenieRightButtonMessage_LikeComp; 
            return this; 
        }
	
        private int? wLDictChangeStatusId;

        /// <summary> 
        /// Gets or sets the WLDictChangeStatusId.
        /// </summary>
        /// <value> WLDictChangeStatusId</value>
        [XmlAttribute]		
        public int? WLDictChangeStatusId
        {
            [DebuggerStepThrough]
            get { return this.wLDictChangeStatusId; }
            [DebuggerStepThrough]
            set { this.wLDictChangeStatusId = value; }
        }
	
        /// <summary> 
        /// Sets the WLDictChangeStatusId value.
        /// </summary>
        /// <value> WLDictChangeStatusId</value>
        public WLTableMessagesFilter SetWLDictChangeStatusId (int? wLDictChangeStatusId)
        {
            this.wLDictChangeStatusId = wLDictChangeStatusId; 
            return this; 
        }
	
        private int? wLDictChangeStatusId_RngLow;

        /// <summary> 
        /// Gets or sets the WLDictChangeStatusId_RngLow.
        /// </summary>
        /// <value> WLDictChangeStatusId_RngLow</value>
				
        public int? WLDictChangeStatusId_RngLow
        {
            [DebuggerStepThrough]
            get { return this.wLDictChangeStatusId_RngLow; }
            [DebuggerStepThrough]
            set { this.wLDictChangeStatusId_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the WLDictChangeStatusId_RngLow value.
        /// </summary>
        /// <value> WLDictChangeStatusId_RngLow</value>
        public WLTableMessagesFilter SetWLDictChangeStatusId_RngLow (int? wLDictChangeStatusId_RngLow)
        {
            this.wLDictChangeStatusId_RngLow = wLDictChangeStatusId_RngLow; 
            return this; 
        }
	
        private int? wLDictChangeStatusId_RngHigh;

        /// <summary> 
        /// Gets or sets the WLDictChangeStatusId_RngHigh.
        /// </summary>
        /// <value> WLDictChangeStatusId_RngHigh</value>
				
        public int? WLDictChangeStatusId_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.wLDictChangeStatusId_RngHigh; }
            [DebuggerStepThrough]
            set { this.wLDictChangeStatusId_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the WLDictChangeStatusId_RngHigh value.
        /// </summary>
        /// <value> WLDictChangeStatusId_RngHigh</value>
        public WLTableMessagesFilter SetWLDictChangeStatusId_RngHigh (int? wLDictChangeStatusId_RngHigh)
        {
            this.wLDictChangeStatusId_RngHigh = wLDictChangeStatusId_RngHigh; 
            return this; 
        }
	
        private FieldsList ord1 = FieldsList.None;
		
        /// <summary> 
        /// Gets or sets the first Order value.
        /// </summary>
        /// <value> FileName</value>
        [XmlAttribute]
        public FieldsList Ord1
        {
            [DebuggerStepThrough]
            get { return this.ord1; }
            [DebuggerStepThrough]
            set { this.ord1 = value; }
        }
		
        /// <summary>
        /// Sets the Ord1 value.
        /// </summary>
        /// <param name="ord1">The ord1.</param>
        /// <returns></returns>
        public WLTableMessagesFilter SetOrd1 (FieldsList ord1)
        {
            this.ord1 = ord1;
            return this; 
        }
		
        private FieldsList ord2 = FieldsList.None;
		
        /// <summary> 
        /// Gets or sets the scnd Order value.
        /// </summary>
        /// <value> FileName</value>
        [XmlAttribute]
        public FieldsList Ord2
        {
            [DebuggerStepThrough]
            get { return this.ord2; }
            [DebuggerStepThrough]
            set { this.ord2 = value; }
        }
		
        /// <summary>
        /// Sets the Ord2 value.
        /// </summary>
        /// <param name="ord2">The ord2.</param>
        /// <returns></returns>
        public WLTableMessagesFilter SetOrd2 (FieldsList ord2)
        {
            this.ord2 = ord2;
            return this; 
        }
		
        private FieldsList ord3 = FieldsList.None;
		
        /// <summary> 
        /// Gets or sets the third Order value.
        /// </summary>
        /// <value> FileName</value>
        [XmlAttribute]
        public FieldsList Ord3
        {
            [DebuggerStepThrough]
            get { return this.ord3; }
            [DebuggerStepThrough]
            set { this.ord3 = value; }
        }
		
        /// <summary>
        /// Sets the Ord3 value.
        /// </summary>
        /// <param name="ord3">The ord3.</param>
        /// <returns></returns>
        public WLTableMessagesFilter SetOrd3 (FieldsList ord3)
        {
            this.ord3 = ord3;
            return this; 
        }
		
        public enum FieldsList : byte
        {
            None = 0, 
            WLTableId = 1, 
            BeachButlerMessage = 2, 
            TableGenieLeftButtonMessage = 3, 
            TableGenieMiddleButtonMessage = 4, 
            TableGenieRightButtonMessage = 5, 
            WLDictChangeStatusId = 6			
        }
	
	
    }
}

// end of namespace

