using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.ComponentModel;

// generated by MyGeneration / DtoTemplate 
// on 2011-11-02 14:51:39

namespace ConApp_VS2k8.Dto
{
    /// <summary>
    /// Dto for WLTable table 
    /// </summary>
    [Serializable]
    public class WLTableDto : ICloneable, IEquatable<WLTableDto>, IEditableObject
    {
        private bool isEdit;
        private bool isModified;
		
        private readonly WLTableDto oldValues;
        
		
        /// <summary>
        /// Gets the dto with old values
        /// </summary>
        /// <value>The old values.</value>
        public WLTableDto OldValues
        {
            get { return oldValues; }
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="WLTableDto"/> class.
        /// Used internally to distinguish between current and old values
        /// </summary>
        /// <param name="isOldValue">if set to <c>true</c> the dto represents the 
        /// inner instance with old values.</param>
        private WLTableDto(bool isOldValue)
        {
            if (! isOldValue)
                oldValues = new WLTableDto(true);
        }

        /// <summary>
        /// Gets a value indicating whether this instance is modified
        /// since last DB read or creation
        /// </summary>
        /// <value>
        /// 	<c>true</c> if this instance is modified; otherwise, <c>false</c>.
        /// </value>
        public bool IsModified
        {
            get { return isModified; }
        }


        private bool isNew = true;
        /// <summary>
        /// Gets a value indicating whether this instance is new.
        /// </summary>
        /// <value><c>true</c> if this instance is new; otherwise, <c>false</c>.</value>
        public bool IsNew
        {
            get { return isNew;}
        }

        /// <summary>
        /// Sets the is new.
        /// </summary>
        /// <param name="isNew">if set to <c>true</c> [is new].</param>
        public void SetIsNew (bool isNew)
        {
            this.isNew = isNew; 
        }
		
        /// <summary>
        /// Sets the is modified flag.
        /// </summary>
        /// <param name="isModified">new value of isModified flag.</param>
        public void SetIsModified(bool isModified)
        {
            this.isModified = isModified;
        }
	
	
        private long id;

        /// <summary> 
        /// Gets or sets the Id.
        /// </summary>
        /// <value> Id</value>
        [XmlAttribute]		
        public long Id
        {
            [DebuggerStepThrough]
            get { return this.id; }
            [DebuggerStepThrough]
            set
            {
                if (!value.Equals(this.id))
                {
                    this.isModified = true;
                    this.id = value;
                }
		
            }
        }
		
	
        private string number;

        /// <summary> 
        /// Gets or sets the Number.
        /// </summary>
        /// <value> Number</value>
        [XmlAttribute]		
        public string Number
        {
            [DebuggerStepThrough]
            get { return this.number; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.number != null)
                     || (value != null && !value.Equals(this.number)))
                {
                    this.isModified = true; 
                    this.number = value;
                }
		
            }
        }
		
	
        private long? waiterWLEmployeeId;

        /// <summary> 
        /// Gets or sets the WaiterWLEmployeeId.
        /// </summary>
        /// <value> WaiterWLEmployeeId</value>
				
        public long? WaiterWLEmployeeId
        {
            [DebuggerStepThrough]
            get { return this.waiterWLEmployeeId; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.waiterWLEmployeeId != null)
                     || (value != null && !value.Equals(this.waiterWLEmployeeId)))
                {
                    this.isModified = true; 
                    this.waiterWLEmployeeId = value;
                }
		
            }
        }
		
	
        private long? managerWLEmployeeId;

        /// <summary> 
        /// Gets or sets the ManagerWLEmployeeId.
        /// </summary>
        /// <value> ManagerWLEmployeeId</value>
				
        public long? ManagerWLEmployeeId
        {
            [DebuggerStepThrough]
            get { return this.managerWLEmployeeId; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.managerWLEmployeeId != null)
                     || (value != null && !value.Equals(this.managerWLEmployeeId)))
                {
                    this.isModified = true; 
                    this.managerWLEmployeeId = value;
                }
		
            }
        }
		
	
        private long wLLocationId;

        /// <summary> 
        /// Gets or sets the WLLocationId.
        /// </summary>
        /// <value> WLLocationId</value>
        [XmlAttribute]		
        public long WLLocationId
        {
            [DebuggerStepThrough]
            get { return this.wLLocationId; }
            [DebuggerStepThrough]
            set
            {
                if (!value.Equals(this.wLLocationId))
                {
                    this.isModified = true;
                    this.wLLocationId = value;
                }
		
            }
        }
		
	
        private long wLDictServiceDeviceId;

        /// <summary> 
        /// Gets or sets the WLDictServiceDeviceId.
        /// </summary>
        /// <value> WLDictServiceDeviceId</value>
        [XmlAttribute]		
        public long WLDictServiceDeviceId
        {
            [DebuggerStepThrough]
            get { return this.wLDictServiceDeviceId; }
            [DebuggerStepThrough]
            set
            {
                if (!value.Equals(this.wLDictServiceDeviceId))
                {
                    this.isModified = true;
                    this.wLDictServiceDeviceId = value;
                }
		
            }
        }
		
	
        private long? beachButlerWhoToPage;

        /// <summary> 
        /// Gets or sets the BeachButlerWhoToPage.
        /// </summary>
        /// <value> BeachButlerWhoToPage</value>
				
        public long? BeachButlerWhoToPage
        {
            [DebuggerStepThrough]
            get { return this.beachButlerWhoToPage; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.beachButlerWhoToPage != null)
                     || (value != null && !value.Equals(this.beachButlerWhoToPage)))
                {
                    this.isModified = true; 
                    this.beachButlerWhoToPage = value;
                }
		
            }
        }
		
	
        private long? tGLeftButtonWhoToPage;

        /// <summary> 
        /// Gets or sets the TGLeftButtonWhoToPage.
        /// </summary>
        /// <value> TGLeftButtonWhoToPage</value>
				
        public long? TGLeftButtonWhoToPage
        {
            [DebuggerStepThrough]
            get { return this.tGLeftButtonWhoToPage; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.tGLeftButtonWhoToPage != null)
                     || (value != null && !value.Equals(this.tGLeftButtonWhoToPage)))
                {
                    this.isModified = true; 
                    this.tGLeftButtonWhoToPage = value;
                }
		
            }
        }
		
	
        private long? tGMiddleButtonWhoToPage;

        /// <summary> 
        /// Gets or sets the TGMiddleButtonWhoToPage.
        /// </summary>
        /// <value> TGMiddleButtonWhoToPage</value>
				
        public long? TGMiddleButtonWhoToPage
        {
            [DebuggerStepThrough]
            get { return this.tGMiddleButtonWhoToPage; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.tGMiddleButtonWhoToPage != null)
                     || (value != null && !value.Equals(this.tGMiddleButtonWhoToPage)))
                {
                    this.isModified = true; 
                    this.tGMiddleButtonWhoToPage = value;
                }
		
            }
        }
		
	
        private long? tGRightButtonWhoToPage;

        /// <summary> 
        /// Gets or sets the TGRightButtonWhoToPage.
        /// </summary>
        /// <value> TGRightButtonWhoToPage</value>
				
        public long? TGRightButtonWhoToPage
        {
            [DebuggerStepThrough]
            get { return this.tGRightButtonWhoToPage; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.tGRightButtonWhoToPage != null)
                     || (value != null && !value.Equals(this.tGRightButtonWhoToPage)))
                {
                    this.isModified = true; 
                    this.tGRightButtonWhoToPage = value;
                }
		
            }
        }
		
	
        private string serialNo;

        /// <summary> 
        /// Gets or sets the SerialNo.
        /// </summary>
        /// <value> SerialNo</value>
				
        public string SerialNo
        {
            [DebuggerStepThrough]
            get { return this.serialNo; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.serialNo != null)
                     || (value != null && !value.Equals(this.serialNo)))
                {
                    this.isModified = true; 
                    this.serialNo = value;
                }
		
            }
        }
		
	
        private long? wLTableId;

        /// <summary> 
        /// Gets or sets the WLTableId.
        /// </summary>
        /// <value> WLTableId</value>
				
        public long? WLTableId
        {
            [DebuggerStepThrough]
            get { return this.wLTableId; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.wLTableId != null)
                     || (value != null && !value.Equals(this.wLTableId)))
                {
                    this.isModified = true; 
                    this.wLTableId = value;
                }
		
            }
        }
		
	
        private long? clientId;

        /// <summary> 
        /// Gets or sets the ClientId.
        /// </summary>
        /// <value> ClientId</value>
				
        public long? ClientId
        {
            [DebuggerStepThrough]
            get { return this.clientId; }
            [DebuggerStepThrough]
            set
            {
                if ( (value == null && this.clientId != null)
                     || (value != null && !value.Equals(this.clientId)))
                {
                    this.isModified = true; 
                    this.clientId = value;
                }
		
            }
        }
		
	
        private int wLDictChangeStatusId;

        /// <summary> 
        /// Gets or sets the WLDictChangeStatusId.
        /// </summary>
        /// <value> WLDictChangeStatusId</value>
        [XmlAttribute]		
        public int WLDictChangeStatusId
        {
            [DebuggerStepThrough]
            get { return this.wLDictChangeStatusId; }
            [DebuggerStepThrough]
            set
            {
                if (!value.Equals(this.wLDictChangeStatusId))
                {
                    this.isModified = true;
                    this.wLDictChangeStatusId = value;
                }
		
            }
        }
		
	
        ///<summary>
        ///Creates a new object that is a copy of the current instance.
        ///</summary>
        ///<returns>A new object that is a copy of this instance.</returns>
        public object Clone()
        {
            return new WLTableDto(this.Id,
                                  this.Number,
                                  this.WaiterWLEmployeeId,
                                  this.ManagerWLEmployeeId,
                                  this.WLLocationId,
                                  this.WLDictServiceDeviceId,
                                  this.BeachButlerWhoToPage,
                                  this.TGLeftButtonWhoToPage,
                                  this.TGMiddleButtonWhoToPage,
                                  this.TGRightButtonWhoToPage,
                                  this.SerialNo,
                                  this.WLTableId,
                                  this.ClientId,
                                  this.WLDictChangeStatusId
                );
        }

        ///<summary>
        ///Indicates whether the current object is equal to another object of the same type.
        ///</summary>
        ///<returns>true if the current object is equal to the other parameter; otherwise, false.</returns>
        ///<param name="other">An object to compare with this object.</param>
        public bool Equals(WLTableDto other)
        {
            if (other == null)
                return false;
				
            return this.id.Equals (other.id)
                   && ( (this.number == null && other.number == null ) || (this.number != null && this.number.Equals (other.number)))
                   && ( (this.waiterWLEmployeeId == null && other.waiterWLEmployeeId == null ) || (this.waiterWLEmployeeId != null && this.waiterWLEmployeeId.Equals (other.waiterWLEmployeeId)))
                   && ( (this.managerWLEmployeeId == null && other.managerWLEmployeeId == null ) || (this.managerWLEmployeeId != null && this.managerWLEmployeeId.Equals (other.managerWLEmployeeId)))
                   && this.wLLocationId.Equals (other.wLLocationId)
                   && this.wLDictServiceDeviceId.Equals (other.wLDictServiceDeviceId)
                   && ( (this.beachButlerWhoToPage == null && other.beachButlerWhoToPage == null ) || (this.beachButlerWhoToPage != null && this.beachButlerWhoToPage.Equals (other.beachButlerWhoToPage)))
                   && ( (this.tGLeftButtonWhoToPage == null && other.tGLeftButtonWhoToPage == null ) || (this.tGLeftButtonWhoToPage != null && this.tGLeftButtonWhoToPage.Equals (other.tGLeftButtonWhoToPage)))
                   && ( (this.tGMiddleButtonWhoToPage == null && other.tGMiddleButtonWhoToPage == null ) || (this.tGMiddleButtonWhoToPage != null && this.tGMiddleButtonWhoToPage.Equals (other.tGMiddleButtonWhoToPage)))
                   && ( (this.tGRightButtonWhoToPage == null && other.tGRightButtonWhoToPage == null ) || (this.tGRightButtonWhoToPage != null && this.tGRightButtonWhoToPage.Equals (other.tGRightButtonWhoToPage)))
                   && ( (this.serialNo == null && other.serialNo == null ) || (this.serialNo != null && this.serialNo.Equals (other.serialNo)))
                   && ( (this.wLTableId == null && other.wLTableId == null ) || (this.wLTableId != null && this.wLTableId.Equals (other.wLTableId)))
                   && ( (this.clientId == null && other.clientId == null ) || (this.clientId != null && this.clientId.Equals (other.clientId)))
                   && this.wLDictChangeStatusId.Equals (other.wLDictChangeStatusId)
                ;
        }
		
        /// <summary>
        /// Copies the property values from another instance
        /// </summary>
        /// <param name="source">The source instance.</param>
        public void CopyProperties(WLTableDto source)
        {
            this.Id = source.Id;
            this.Number = source.Number;
            this.WaiterWLEmployeeId = source.WaiterWLEmployeeId;
            this.ManagerWLEmployeeId = source.ManagerWLEmployeeId;
            this.WLLocationId = source.WLLocationId;
            this.WLDictServiceDeviceId = source.WLDictServiceDeviceId;
            this.BeachButlerWhoToPage = source.BeachButlerWhoToPage;
            this.TGLeftButtonWhoToPage = source.TGLeftButtonWhoToPage;
            this.TGMiddleButtonWhoToPage = source.TGMiddleButtonWhoToPage;
            this.TGRightButtonWhoToPage = source.TGRightButtonWhoToPage;
            this.SerialNo = source.SerialNo;
            this.WLTableId = source.WLTableId;
            this.ClientId = source.ClientId;
            this.WLDictChangeStatusId = source.WLDictChangeStatusId;

        }



        /// <summary>
        /// Initializes a new instance of the <see cref="WLTableDto"/> class.
        /// All values can be provided
        /// </summary>
        ///<param name="id">WLTable.id</param>
        ///<param name="number">WLTable.number</param>
        ///<param name="waiterWLEmployeeId">WLTable.waiterWLEmployeeId</param>
        ///<param name="managerWLEmployeeId">WLTable.managerWLEmployeeId</param>
        ///<param name="wLLocationId">WLTable.wLLocationId</param>
        ///<param name="wLDictServiceDeviceId">WLTable.wLDictServiceDeviceId</param>
        ///<param name="beachButlerWhoToPage">WLTable.beachButlerWhoToPage</param>
        ///<param name="tGLeftButtonWhoToPage">WLTable.tGLeftButtonWhoToPage</param>
        ///<param name="tGMiddleButtonWhoToPage">WLTable.tGMiddleButtonWhoToPage</param>
        ///<param name="tGRightButtonWhoToPage">WLTable.tGRightButtonWhoToPage</param>
        ///<param name="serialNo">WLTable.serialNo</param>
        ///<param name="wLTableId">WLTable.wLTableId</param>
        ///<param name="clientId">WLTable.clientId</param>
        ///<param name="wLDictChangeStatusId">WLTable.wLDictChangeStatusId</param>

        public WLTableDto(long id, string number, long? waiterWLEmployeeId, long? managerWLEmployeeId, long wLLocationId, long wLDictServiceDeviceId, long? beachButlerWhoToPage, long? tGLeftButtonWhoToPage, long? tGMiddleButtonWhoToPage, long? tGRightButtonWhoToPage, string serialNo, long? wLTableId, long? clientId, int wLDictChangeStatusId) : this(false)
        {
            this.id = id;
            this.number = number;
            this.waiterWLEmployeeId = waiterWLEmployeeId;
            this.managerWLEmployeeId = managerWLEmployeeId;
            this.wLLocationId = wLLocationId;
            this.wLDictServiceDeviceId = wLDictServiceDeviceId;
            this.beachButlerWhoToPage = beachButlerWhoToPage;
            this.tGLeftButtonWhoToPage = tGLeftButtonWhoToPage;
            this.tGMiddleButtonWhoToPage = tGMiddleButtonWhoToPage;
            this.tGRightButtonWhoToPage = tGRightButtonWhoToPage;
            this.serialNo = serialNo;
            this.wLTableId = wLTableId;
            this.clientId = clientId;
            this.wLDictChangeStatusId = wLDictChangeStatusId;
			
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="WLTableDto"/> class;
        /// creates new (empty) DTO
        /// Not null values can be provided
        /// </summary>
        public WLTableDto(long id, string number, long wLLocationId, long wLDictServiceDeviceId, int wLDictChangeStatusId) : this(false)
        {
            this.id = id;
            this.number = number;
            this.wLLocationId = wLLocationId;
            this.wLDictServiceDeviceId = wLDictServiceDeviceId;
            this.wLDictChangeStatusId = wLDictChangeStatusId;

        }

		
        /// <summary>
        /// Initializes a new instance of the <see cref="WLTableDto"/> class;
        /// creates new (empty) DTO
        /// Parameterless cstr - avoid using it if no nocessary!
        /// </summary>
        public WLTableDto() : this(false)
        {
        }
		
        ///<summary>
        ///Begins an edit on an object.
        ///</summary>
        ///
        public void BeginEdit()
        {
            if (!isEdit)
            {
                isEdit = true;
                this.OldValues.CopyProperties(this);
            }
        }

        ///<summary>
        ///Pushes changes since the last <see cref="M:System.ComponentModel.IEditableObject.BeginEdit"></see> 
        /// or <see cref="M:System.ComponentModel.IBindingList.AddNew"></see> call into the underlying object.
        ///</summary>
        public void EndEdit()
        {
            isEdit = false;
        }

        ///<summary>
        ///Discards changes since the last <see cref="M:System.ComponentModel.IEditableObject.BeginEdit"></see> call.
        ///</summary>
        public void CancelEdit()
        {
            if (isEdit)
            {
                this.CopyProperties(this.OldValues);
                isEdit = false;
            }
        }
    }

    /// <summary>
    /// List of WLTableDto
    /// </summary>
    [Serializable]
    public class WLTableCollection : BindingList<WLTableDto>
    {
	
        /// <summary>
        /// Finds dto in collection by specified key values; null if no object matching
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns>found dto or null if not found</returns>
        public WLTableDto FindById (long id)
        {
            foreach (WLTableDto dto in this)
                if (dto.Id == id)
                    return dto;
            return null; 
        }
	
    }

    /// <summary>
    /// Filter for WLTableDto
    /// </summary>
    [Serializable]
    public class WLTableFilter
    {

        private long? id;

        /// <summary> 
        /// Gets or sets the Id.
        /// </summary>
        /// <value> Id</value>
        [XmlAttribute]		
        public long? Id
        {
            [DebuggerStepThrough]
            get { return this.id; }
            [DebuggerStepThrough]
            set { this.id = value; }
        }
	
        /// <summary> 
        /// Sets the Id value.
        /// </summary>
        /// <value> Id</value>
        public WLTableFilter SetId (long? id)
        {
            this.id = id; 
            return this; 
        }
	
        private long? id_RngLow;

        /// <summary> 
        /// Gets or sets the Id_RngLow.
        /// </summary>
        /// <value> Id_RngLow</value>
				
        public long? Id_RngLow
        {
            [DebuggerStepThrough]
            get { return this.id_RngLow; }
            [DebuggerStepThrough]
            set { this.id_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the Id_RngLow value.
        /// </summary>
        /// <value> Id_RngLow</value>
        public WLTableFilter SetId_RngLow (long? id_RngLow)
        {
            this.id_RngLow = id_RngLow; 
            return this; 
        }
	
        private long? id_RngHigh;

        /// <summary> 
        /// Gets or sets the Id_RngHigh.
        /// </summary>
        /// <value> Id_RngHigh</value>
				
        public long? Id_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.id_RngHigh; }
            [DebuggerStepThrough]
            set { this.id_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the Id_RngHigh value.
        /// </summary>
        /// <value> Id_RngHigh</value>
        public WLTableFilter SetId_RngHigh (long? id_RngHigh)
        {
            this.id_RngHigh = id_RngHigh; 
            return this; 
        }
	
        private string number;

        /// <summary> 
        /// Gets or sets the Number.
        /// </summary>
        /// <value> Number</value>
        [XmlAttribute]		
        public string Number
        {
            [DebuggerStepThrough]
            get { return this.number; }
            [DebuggerStepThrough]
            set { this.number = value; }
        }
	
        /// <summary> 
        /// Sets the Number value.
        /// </summary>
        /// <value> Number</value>
        public WLTableFilter SetNumber (string number)
        {
            this.number = number; 
            return this; 
        }
	
        private string number_LikeComp;

        /// <summary> 
        /// Gets or sets the Number_LikeComp.
        /// </summary>
        /// <value> Number_LikeComp</value>
				
        public string Number_LikeComp
        {
            [DebuggerStepThrough]
            get { return this.number_LikeComp; }
            [DebuggerStepThrough]
            set { this.number_LikeComp = value; }
        }
	
        /// <summary> 
        /// Sets the Number_LikeComp value.
        /// </summary>
        /// <value> Number_LikeComp</value>
        public WLTableFilter SetNumber_LikeComp (string number_LikeComp)
        {
            this.number_LikeComp = number_LikeComp; 
            return this; 
        }
	
        private long? waiterWLEmployeeId;

        /// <summary> 
        /// Gets or sets the WaiterWLEmployeeId.
        /// </summary>
        /// <value> WaiterWLEmployeeId</value>
				
        public long? WaiterWLEmployeeId
        {
            [DebuggerStepThrough]
            get { return this.waiterWLEmployeeId; }
            [DebuggerStepThrough]
            set { this.waiterWLEmployeeId = value; }
        }
	
        /// <summary> 
        /// Sets the WaiterWLEmployeeId value.
        /// </summary>
        /// <value> WaiterWLEmployeeId</value>
        public WLTableFilter SetWaiterWLEmployeeId (long? waiterWLEmployeeId)
        {
            this.waiterWLEmployeeId = waiterWLEmployeeId; 
            return this; 
        }
	
        private long? waiterWLEmployeeId_RngLow;

        /// <summary> 
        /// Gets or sets the WaiterWLEmployeeId_RngLow.
        /// </summary>
        /// <value> WaiterWLEmployeeId_RngLow</value>
				
        public long? WaiterWLEmployeeId_RngLow
        {
            [DebuggerStepThrough]
            get { return this.waiterWLEmployeeId_RngLow; }
            [DebuggerStepThrough]
            set { this.waiterWLEmployeeId_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the WaiterWLEmployeeId_RngLow value.
        /// </summary>
        /// <value> WaiterWLEmployeeId_RngLow</value>
        public WLTableFilter SetWaiterWLEmployeeId_RngLow (long? waiterWLEmployeeId_RngLow)
        {
            this.waiterWLEmployeeId_RngLow = waiterWLEmployeeId_RngLow; 
            return this; 
        }
	
        private long? waiterWLEmployeeId_RngHigh;

        /// <summary> 
        /// Gets or sets the WaiterWLEmployeeId_RngHigh.
        /// </summary>
        /// <value> WaiterWLEmployeeId_RngHigh</value>
				
        public long? WaiterWLEmployeeId_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.waiterWLEmployeeId_RngHigh; }
            [DebuggerStepThrough]
            set { this.waiterWLEmployeeId_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the WaiterWLEmployeeId_RngHigh value.
        /// </summary>
        /// <value> WaiterWLEmployeeId_RngHigh</value>
        public WLTableFilter SetWaiterWLEmployeeId_RngHigh (long? waiterWLEmployeeId_RngHigh)
        {
            this.waiterWLEmployeeId_RngHigh = waiterWLEmployeeId_RngHigh; 
            return this; 
        }
	
        private long? managerWLEmployeeId;

        /// <summary> 
        /// Gets or sets the ManagerWLEmployeeId.
        /// </summary>
        /// <value> ManagerWLEmployeeId</value>
				
        public long? ManagerWLEmployeeId
        {
            [DebuggerStepThrough]
            get { return this.managerWLEmployeeId; }
            [DebuggerStepThrough]
            set { this.managerWLEmployeeId = value; }
        }
	
        /// <summary> 
        /// Sets the ManagerWLEmployeeId value.
        /// </summary>
        /// <value> ManagerWLEmployeeId</value>
        public WLTableFilter SetManagerWLEmployeeId (long? managerWLEmployeeId)
        {
            this.managerWLEmployeeId = managerWLEmployeeId; 
            return this; 
        }
	
        private long? managerWLEmployeeId_RngLow;

        /// <summary> 
        /// Gets or sets the ManagerWLEmployeeId_RngLow.
        /// </summary>
        /// <value> ManagerWLEmployeeId_RngLow</value>
				
        public long? ManagerWLEmployeeId_RngLow
        {
            [DebuggerStepThrough]
            get { return this.managerWLEmployeeId_RngLow; }
            [DebuggerStepThrough]
            set { this.managerWLEmployeeId_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the ManagerWLEmployeeId_RngLow value.
        /// </summary>
        /// <value> ManagerWLEmployeeId_RngLow</value>
        public WLTableFilter SetManagerWLEmployeeId_RngLow (long? managerWLEmployeeId_RngLow)
        {
            this.managerWLEmployeeId_RngLow = managerWLEmployeeId_RngLow; 
            return this; 
        }
	
        private long? managerWLEmployeeId_RngHigh;

        /// <summary> 
        /// Gets or sets the ManagerWLEmployeeId_RngHigh.
        /// </summary>
        /// <value> ManagerWLEmployeeId_RngHigh</value>
				
        public long? ManagerWLEmployeeId_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.managerWLEmployeeId_RngHigh; }
            [DebuggerStepThrough]
            set { this.managerWLEmployeeId_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the ManagerWLEmployeeId_RngHigh value.
        /// </summary>
        /// <value> ManagerWLEmployeeId_RngHigh</value>
        public WLTableFilter SetManagerWLEmployeeId_RngHigh (long? managerWLEmployeeId_RngHigh)
        {
            this.managerWLEmployeeId_RngHigh = managerWLEmployeeId_RngHigh; 
            return this; 
        }
	
        private long? wLLocationId;

        /// <summary> 
        /// Gets or sets the WLLocationId.
        /// </summary>
        /// <value> WLLocationId</value>
        [XmlAttribute]		
        public long? WLLocationId
        {
            [DebuggerStepThrough]
            get { return this.wLLocationId; }
            [DebuggerStepThrough]
            set { this.wLLocationId = value; }
        }
	
        /// <summary> 
        /// Sets the WLLocationId value.
        /// </summary>
        /// <value> WLLocationId</value>
        public WLTableFilter SetWLLocationId (long? wLLocationId)
        {
            this.wLLocationId = wLLocationId; 
            return this; 
        }
	
        private long? wLLocationId_RngLow;

        /// <summary> 
        /// Gets or sets the WLLocationId_RngLow.
        /// </summary>
        /// <value> WLLocationId_RngLow</value>
				
        public long? WLLocationId_RngLow
        {
            [DebuggerStepThrough]
            get { return this.wLLocationId_RngLow; }
            [DebuggerStepThrough]
            set { this.wLLocationId_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the WLLocationId_RngLow value.
        /// </summary>
        /// <value> WLLocationId_RngLow</value>
        public WLTableFilter SetWLLocationId_RngLow (long? wLLocationId_RngLow)
        {
            this.wLLocationId_RngLow = wLLocationId_RngLow; 
            return this; 
        }
	
        private long? wLLocationId_RngHigh;

        /// <summary> 
        /// Gets or sets the WLLocationId_RngHigh.
        /// </summary>
        /// <value> WLLocationId_RngHigh</value>
				
        public long? WLLocationId_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.wLLocationId_RngHigh; }
            [DebuggerStepThrough]
            set { this.wLLocationId_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the WLLocationId_RngHigh value.
        /// </summary>
        /// <value> WLLocationId_RngHigh</value>
        public WLTableFilter SetWLLocationId_RngHigh (long? wLLocationId_RngHigh)
        {
            this.wLLocationId_RngHigh = wLLocationId_RngHigh; 
            return this; 
        }
	
        private long? wLDictServiceDeviceId;

        /// <summary> 
        /// Gets or sets the WLDictServiceDeviceId.
        /// </summary>
        /// <value> WLDictServiceDeviceId</value>
        [XmlAttribute]		
        public long? WLDictServiceDeviceId
        {
            [DebuggerStepThrough]
            get { return this.wLDictServiceDeviceId; }
            [DebuggerStepThrough]
            set { this.wLDictServiceDeviceId = value; }
        }
	
        /// <summary> 
        /// Sets the WLDictServiceDeviceId value.
        /// </summary>
        /// <value> WLDictServiceDeviceId</value>
        public WLTableFilter SetWLDictServiceDeviceId (long? wLDictServiceDeviceId)
        {
            this.wLDictServiceDeviceId = wLDictServiceDeviceId; 
            return this; 
        }
	
        private long? wLDictServiceDeviceId_RngLow;

        /// <summary> 
        /// Gets or sets the WLDictServiceDeviceId_RngLow.
        /// </summary>
        /// <value> WLDictServiceDeviceId_RngLow</value>
				
        public long? WLDictServiceDeviceId_RngLow
        {
            [DebuggerStepThrough]
            get { return this.wLDictServiceDeviceId_RngLow; }
            [DebuggerStepThrough]
            set { this.wLDictServiceDeviceId_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the WLDictServiceDeviceId_RngLow value.
        /// </summary>
        /// <value> WLDictServiceDeviceId_RngLow</value>
        public WLTableFilter SetWLDictServiceDeviceId_RngLow (long? wLDictServiceDeviceId_RngLow)
        {
            this.wLDictServiceDeviceId_RngLow = wLDictServiceDeviceId_RngLow; 
            return this; 
        }
	
        private long? wLDictServiceDeviceId_RngHigh;

        /// <summary> 
        /// Gets or sets the WLDictServiceDeviceId_RngHigh.
        /// </summary>
        /// <value> WLDictServiceDeviceId_RngHigh</value>
				
        public long? WLDictServiceDeviceId_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.wLDictServiceDeviceId_RngHigh; }
            [DebuggerStepThrough]
            set { this.wLDictServiceDeviceId_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the WLDictServiceDeviceId_RngHigh value.
        /// </summary>
        /// <value> WLDictServiceDeviceId_RngHigh</value>
        public WLTableFilter SetWLDictServiceDeviceId_RngHigh (long? wLDictServiceDeviceId_RngHigh)
        {
            this.wLDictServiceDeviceId_RngHigh = wLDictServiceDeviceId_RngHigh; 
            return this; 
        }
	
        private long? beachButlerWhoToPage;

        /// <summary> 
        /// Gets or sets the BeachButlerWhoToPage.
        /// </summary>
        /// <value> BeachButlerWhoToPage</value>
				
        public long? BeachButlerWhoToPage
        {
            [DebuggerStepThrough]
            get { return this.beachButlerWhoToPage; }
            [DebuggerStepThrough]
            set { this.beachButlerWhoToPage = value; }
        }
	
        /// <summary> 
        /// Sets the BeachButlerWhoToPage value.
        /// </summary>
        /// <value> BeachButlerWhoToPage</value>
        public WLTableFilter SetBeachButlerWhoToPage (long? beachButlerWhoToPage)
        {
            this.beachButlerWhoToPage = beachButlerWhoToPage; 
            return this; 
        }
	
        private long? beachButlerWhoToPage_RngLow;

        /// <summary> 
        /// Gets or sets the BeachButlerWhoToPage_RngLow.
        /// </summary>
        /// <value> BeachButlerWhoToPage_RngLow</value>
				
        public long? BeachButlerWhoToPage_RngLow
        {
            [DebuggerStepThrough]
            get { return this.beachButlerWhoToPage_RngLow; }
            [DebuggerStepThrough]
            set { this.beachButlerWhoToPage_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the BeachButlerWhoToPage_RngLow value.
        /// </summary>
        /// <value> BeachButlerWhoToPage_RngLow</value>
        public WLTableFilter SetBeachButlerWhoToPage_RngLow (long? beachButlerWhoToPage_RngLow)
        {
            this.beachButlerWhoToPage_RngLow = beachButlerWhoToPage_RngLow; 
            return this; 
        }
	
        private long? beachButlerWhoToPage_RngHigh;

        /// <summary> 
        /// Gets or sets the BeachButlerWhoToPage_RngHigh.
        /// </summary>
        /// <value> BeachButlerWhoToPage_RngHigh</value>
				
        public long? BeachButlerWhoToPage_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.beachButlerWhoToPage_RngHigh; }
            [DebuggerStepThrough]
            set { this.beachButlerWhoToPage_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the BeachButlerWhoToPage_RngHigh value.
        /// </summary>
        /// <value> BeachButlerWhoToPage_RngHigh</value>
        public WLTableFilter SetBeachButlerWhoToPage_RngHigh (long? beachButlerWhoToPage_RngHigh)
        {
            this.beachButlerWhoToPage_RngHigh = beachButlerWhoToPage_RngHigh; 
            return this; 
        }
	
        private long? tGLeftButtonWhoToPage;

        /// <summary> 
        /// Gets or sets the TGLeftButtonWhoToPage.
        /// </summary>
        /// <value> TGLeftButtonWhoToPage</value>
				
        public long? TGLeftButtonWhoToPage
        {
            [DebuggerStepThrough]
            get { return this.tGLeftButtonWhoToPage; }
            [DebuggerStepThrough]
            set { this.tGLeftButtonWhoToPage = value; }
        }
	
        /// <summary> 
        /// Sets the TGLeftButtonWhoToPage value.
        /// </summary>
        /// <value> TGLeftButtonWhoToPage</value>
        public WLTableFilter SetTGLeftButtonWhoToPage (long? tGLeftButtonWhoToPage)
        {
            this.tGLeftButtonWhoToPage = tGLeftButtonWhoToPage; 
            return this; 
        }
	
        private long? tGLeftButtonWhoToPage_RngLow;

        /// <summary> 
        /// Gets or sets the TGLeftButtonWhoToPage_RngLow.
        /// </summary>
        /// <value> TGLeftButtonWhoToPage_RngLow</value>
				
        public long? TGLeftButtonWhoToPage_RngLow
        {
            [DebuggerStepThrough]
            get { return this.tGLeftButtonWhoToPage_RngLow; }
            [DebuggerStepThrough]
            set { this.tGLeftButtonWhoToPage_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the TGLeftButtonWhoToPage_RngLow value.
        /// </summary>
        /// <value> TGLeftButtonWhoToPage_RngLow</value>
        public WLTableFilter SetTGLeftButtonWhoToPage_RngLow (long? tGLeftButtonWhoToPage_RngLow)
        {
            this.tGLeftButtonWhoToPage_RngLow = tGLeftButtonWhoToPage_RngLow; 
            return this; 
        }
	
        private long? tGLeftButtonWhoToPage_RngHigh;

        /// <summary> 
        /// Gets or sets the TGLeftButtonWhoToPage_RngHigh.
        /// </summary>
        /// <value> TGLeftButtonWhoToPage_RngHigh</value>
				
        public long? TGLeftButtonWhoToPage_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.tGLeftButtonWhoToPage_RngHigh; }
            [DebuggerStepThrough]
            set { this.tGLeftButtonWhoToPage_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the TGLeftButtonWhoToPage_RngHigh value.
        /// </summary>
        /// <value> TGLeftButtonWhoToPage_RngHigh</value>
        public WLTableFilter SetTGLeftButtonWhoToPage_RngHigh (long? tGLeftButtonWhoToPage_RngHigh)
        {
            this.tGLeftButtonWhoToPage_RngHigh = tGLeftButtonWhoToPage_RngHigh; 
            return this; 
        }
	
        private long? tGMiddleButtonWhoToPage;

        /// <summary> 
        /// Gets or sets the TGMiddleButtonWhoToPage.
        /// </summary>
        /// <value> TGMiddleButtonWhoToPage</value>
				
        public long? TGMiddleButtonWhoToPage
        {
            [DebuggerStepThrough]
            get { return this.tGMiddleButtonWhoToPage; }
            [DebuggerStepThrough]
            set { this.tGMiddleButtonWhoToPage = value; }
        }
	
        /// <summary> 
        /// Sets the TGMiddleButtonWhoToPage value.
        /// </summary>
        /// <value> TGMiddleButtonWhoToPage</value>
        public WLTableFilter SetTGMiddleButtonWhoToPage (long? tGMiddleButtonWhoToPage)
        {
            this.tGMiddleButtonWhoToPage = tGMiddleButtonWhoToPage; 
            return this; 
        }
	
        private long? tGMiddleButtonWhoToPage_RngLow;

        /// <summary> 
        /// Gets or sets the TGMiddleButtonWhoToPage_RngLow.
        /// </summary>
        /// <value> TGMiddleButtonWhoToPage_RngLow</value>
				
        public long? TGMiddleButtonWhoToPage_RngLow
        {
            [DebuggerStepThrough]
            get { return this.tGMiddleButtonWhoToPage_RngLow; }
            [DebuggerStepThrough]
            set { this.tGMiddleButtonWhoToPage_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the TGMiddleButtonWhoToPage_RngLow value.
        /// </summary>
        /// <value> TGMiddleButtonWhoToPage_RngLow</value>
        public WLTableFilter SetTGMiddleButtonWhoToPage_RngLow (long? tGMiddleButtonWhoToPage_RngLow)
        {
            this.tGMiddleButtonWhoToPage_RngLow = tGMiddleButtonWhoToPage_RngLow; 
            return this; 
        }
	
        private long? tGMiddleButtonWhoToPage_RngHigh;

        /// <summary> 
        /// Gets or sets the TGMiddleButtonWhoToPage_RngHigh.
        /// </summary>
        /// <value> TGMiddleButtonWhoToPage_RngHigh</value>
				
        public long? TGMiddleButtonWhoToPage_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.tGMiddleButtonWhoToPage_RngHigh; }
            [DebuggerStepThrough]
            set { this.tGMiddleButtonWhoToPage_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the TGMiddleButtonWhoToPage_RngHigh value.
        /// </summary>
        /// <value> TGMiddleButtonWhoToPage_RngHigh</value>
        public WLTableFilter SetTGMiddleButtonWhoToPage_RngHigh (long? tGMiddleButtonWhoToPage_RngHigh)
        {
            this.tGMiddleButtonWhoToPage_RngHigh = tGMiddleButtonWhoToPage_RngHigh; 
            return this; 
        }
	
        private long? tGRightButtonWhoToPage;

        /// <summary> 
        /// Gets or sets the TGRightButtonWhoToPage.
        /// </summary>
        /// <value> TGRightButtonWhoToPage</value>
				
        public long? TGRightButtonWhoToPage
        {
            [DebuggerStepThrough]
            get { return this.tGRightButtonWhoToPage; }
            [DebuggerStepThrough]
            set { this.tGRightButtonWhoToPage = value; }
        }
	
        /// <summary> 
        /// Sets the TGRightButtonWhoToPage value.
        /// </summary>
        /// <value> TGRightButtonWhoToPage</value>
        public WLTableFilter SetTGRightButtonWhoToPage (long? tGRightButtonWhoToPage)
        {
            this.tGRightButtonWhoToPage = tGRightButtonWhoToPage; 
            return this; 
        }
	
        private long? tGRightButtonWhoToPage_RngLow;

        /// <summary> 
        /// Gets or sets the TGRightButtonWhoToPage_RngLow.
        /// </summary>
        /// <value> TGRightButtonWhoToPage_RngLow</value>
				
        public long? TGRightButtonWhoToPage_RngLow
        {
            [DebuggerStepThrough]
            get { return this.tGRightButtonWhoToPage_RngLow; }
            [DebuggerStepThrough]
            set { this.tGRightButtonWhoToPage_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the TGRightButtonWhoToPage_RngLow value.
        /// </summary>
        /// <value> TGRightButtonWhoToPage_RngLow</value>
        public WLTableFilter SetTGRightButtonWhoToPage_RngLow (long? tGRightButtonWhoToPage_RngLow)
        {
            this.tGRightButtonWhoToPage_RngLow = tGRightButtonWhoToPage_RngLow; 
            return this; 
        }
	
        private long? tGRightButtonWhoToPage_RngHigh;

        /// <summary> 
        /// Gets or sets the TGRightButtonWhoToPage_RngHigh.
        /// </summary>
        /// <value> TGRightButtonWhoToPage_RngHigh</value>
				
        public long? TGRightButtonWhoToPage_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.tGRightButtonWhoToPage_RngHigh; }
            [DebuggerStepThrough]
            set { this.tGRightButtonWhoToPage_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the TGRightButtonWhoToPage_RngHigh value.
        /// </summary>
        /// <value> TGRightButtonWhoToPage_RngHigh</value>
        public WLTableFilter SetTGRightButtonWhoToPage_RngHigh (long? tGRightButtonWhoToPage_RngHigh)
        {
            this.tGRightButtonWhoToPage_RngHigh = tGRightButtonWhoToPage_RngHigh; 
            return this; 
        }
	
        private string serialNo;

        /// <summary> 
        /// Gets or sets the SerialNo.
        /// </summary>
        /// <value> SerialNo</value>
				
        public string SerialNo
        {
            [DebuggerStepThrough]
            get { return this.serialNo; }
            [DebuggerStepThrough]
            set { this.serialNo = value; }
        }
	
        /// <summary> 
        /// Sets the SerialNo value.
        /// </summary>
        /// <value> SerialNo</value>
        public WLTableFilter SetSerialNo (string serialNo)
        {
            this.serialNo = serialNo; 
            return this; 
        }
	
        private string serialNo_LikeComp;

        /// <summary> 
        /// Gets or sets the SerialNo_LikeComp.
        /// </summary>
        /// <value> SerialNo_LikeComp</value>
				
        public string SerialNo_LikeComp
        {
            [DebuggerStepThrough]
            get { return this.serialNo_LikeComp; }
            [DebuggerStepThrough]
            set { this.serialNo_LikeComp = value; }
        }
	
        /// <summary> 
        /// Sets the SerialNo_LikeComp value.
        /// </summary>
        /// <value> SerialNo_LikeComp</value>
        public WLTableFilter SetSerialNo_LikeComp (string serialNo_LikeComp)
        {
            this.serialNo_LikeComp = serialNo_LikeComp; 
            return this; 
        }
	
        private long? wLTableId;

        /// <summary> 
        /// Gets or sets the WLTableId.
        /// </summary>
        /// <value> WLTableId</value>
				
        public long? WLTableId
        {
            [DebuggerStepThrough]
            get { return this.wLTableId; }
            [DebuggerStepThrough]
            set { this.wLTableId = value; }
        }
	
        /// <summary> 
        /// Sets the WLTableId value.
        /// </summary>
        /// <value> WLTableId</value>
        public WLTableFilter SetWLTableId (long? wLTableId)
        {
            this.wLTableId = wLTableId; 
            return this; 
        }
	
        private long? wLTableId_RngLow;

        /// <summary> 
        /// Gets or sets the WLTableId_RngLow.
        /// </summary>
        /// <value> WLTableId_RngLow</value>
				
        public long? WLTableId_RngLow
        {
            [DebuggerStepThrough]
            get { return this.wLTableId_RngLow; }
            [DebuggerStepThrough]
            set { this.wLTableId_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the WLTableId_RngLow value.
        /// </summary>
        /// <value> WLTableId_RngLow</value>
        public WLTableFilter SetWLTableId_RngLow (long? wLTableId_RngLow)
        {
            this.wLTableId_RngLow = wLTableId_RngLow; 
            return this; 
        }
	
        private long? wLTableId_RngHigh;

        /// <summary> 
        /// Gets or sets the WLTableId_RngHigh.
        /// </summary>
        /// <value> WLTableId_RngHigh</value>
				
        public long? WLTableId_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.wLTableId_RngHigh; }
            [DebuggerStepThrough]
            set { this.wLTableId_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the WLTableId_RngHigh value.
        /// </summary>
        /// <value> WLTableId_RngHigh</value>
        public WLTableFilter SetWLTableId_RngHigh (long? wLTableId_RngHigh)
        {
            this.wLTableId_RngHigh = wLTableId_RngHigh; 
            return this; 
        }
	
        private long? clientId;

        /// <summary> 
        /// Gets or sets the ClientId.
        /// </summary>
        /// <value> ClientId</value>
				
        public long? ClientId
        {
            [DebuggerStepThrough]
            get { return this.clientId; }
            [DebuggerStepThrough]
            set { this.clientId = value; }
        }
	
        /// <summary> 
        /// Sets the ClientId value.
        /// </summary>
        /// <value> ClientId</value>
        public WLTableFilter SetClientId (long? clientId)
        {
            this.clientId = clientId; 
            return this; 
        }
	
        private long? clientId_RngLow;

        /// <summary> 
        /// Gets or sets the ClientId_RngLow.
        /// </summary>
        /// <value> ClientId_RngLow</value>
				
        public long? ClientId_RngLow
        {
            [DebuggerStepThrough]
            get { return this.clientId_RngLow; }
            [DebuggerStepThrough]
            set { this.clientId_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the ClientId_RngLow value.
        /// </summary>
        /// <value> ClientId_RngLow</value>
        public WLTableFilter SetClientId_RngLow (long? clientId_RngLow)
        {
            this.clientId_RngLow = clientId_RngLow; 
            return this; 
        }
	
        private long? clientId_RngHigh;

        /// <summary> 
        /// Gets or sets the ClientId_RngHigh.
        /// </summary>
        /// <value> ClientId_RngHigh</value>
				
        public long? ClientId_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.clientId_RngHigh; }
            [DebuggerStepThrough]
            set { this.clientId_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the ClientId_RngHigh value.
        /// </summary>
        /// <value> ClientId_RngHigh</value>
        public WLTableFilter SetClientId_RngHigh (long? clientId_RngHigh)
        {
            this.clientId_RngHigh = clientId_RngHigh; 
            return this; 
        }
	
        private int? wLDictChangeStatusId;

        /// <summary> 
        /// Gets or sets the WLDictChangeStatusId.
        /// </summary>
        /// <value> WLDictChangeStatusId</value>
        [XmlAttribute]		
        public int? WLDictChangeStatusId
        {
            [DebuggerStepThrough]
            get { return this.wLDictChangeStatusId; }
            [DebuggerStepThrough]
            set { this.wLDictChangeStatusId = value; }
        }
	
        /// <summary> 
        /// Sets the WLDictChangeStatusId value.
        /// </summary>
        /// <value> WLDictChangeStatusId</value>
        public WLTableFilter SetWLDictChangeStatusId (int? wLDictChangeStatusId)
        {
            this.wLDictChangeStatusId = wLDictChangeStatusId; 
            return this; 
        }
	
        private int? wLDictChangeStatusId_RngLow;

        /// <summary> 
        /// Gets or sets the WLDictChangeStatusId_RngLow.
        /// </summary>
        /// <value> WLDictChangeStatusId_RngLow</value>
				
        public int? WLDictChangeStatusId_RngLow
        {
            [DebuggerStepThrough]
            get { return this.wLDictChangeStatusId_RngLow; }
            [DebuggerStepThrough]
            set { this.wLDictChangeStatusId_RngLow = value; }
        }
	
        /// <summary> 
        /// Sets the WLDictChangeStatusId_RngLow value.
        /// </summary>
        /// <value> WLDictChangeStatusId_RngLow</value>
        public WLTableFilter SetWLDictChangeStatusId_RngLow (int? wLDictChangeStatusId_RngLow)
        {
            this.wLDictChangeStatusId_RngLow = wLDictChangeStatusId_RngLow; 
            return this; 
        }
	
        private int? wLDictChangeStatusId_RngHigh;

        /// <summary> 
        /// Gets or sets the WLDictChangeStatusId_RngHigh.
        /// </summary>
        /// <value> WLDictChangeStatusId_RngHigh</value>
				
        public int? WLDictChangeStatusId_RngHigh
        {
            [DebuggerStepThrough]
            get { return this.wLDictChangeStatusId_RngHigh; }
            [DebuggerStepThrough]
            set { this.wLDictChangeStatusId_RngHigh = value; }
        }
	
        /// <summary> 
        /// Sets the WLDictChangeStatusId_RngHigh value.
        /// </summary>
        /// <value> WLDictChangeStatusId_RngHigh</value>
        public WLTableFilter SetWLDictChangeStatusId_RngHigh (int? wLDictChangeStatusId_RngHigh)
        {
            this.wLDictChangeStatusId_RngHigh = wLDictChangeStatusId_RngHigh; 
            return this; 
        }
	
        private FieldsList ord1 = FieldsList.None;
		
        /// <summary> 
        /// Gets or sets the first Order value.
        /// </summary>
        /// <value> FileName</value>
        [XmlAttribute]
        public FieldsList Ord1
        {
            [DebuggerStepThrough]
            get { return this.ord1; }
            [DebuggerStepThrough]
            set { this.ord1 = value; }
        }
		
        /// <summary>
        /// Sets the Ord1 value.
        /// </summary>
        /// <param name="ord1">The ord1.</param>
        /// <returns></returns>
        public WLTableFilter SetOrd1 (FieldsList ord1)
        {
            this.ord1 = ord1;
            return this; 
        }
		
        private FieldsList ord2 = FieldsList.None;
		
        /// <summary> 
        /// Gets or sets the scnd Order value.
        /// </summary>
        /// <value> FileName</value>
        [XmlAttribute]
        public FieldsList Ord2
        {
            [DebuggerStepThrough]
            get { return this.ord2; }
            [DebuggerStepThrough]
            set { this.ord2 = value; }
        }
		
        /// <summary>
        /// Sets the Ord2 value.
        /// </summary>
        /// <param name="ord2">The ord2.</param>
        /// <returns></returns>
        public WLTableFilter SetOrd2 (FieldsList ord2)
        {
            this.ord2 = ord2;
            return this; 
        }
		
        private FieldsList ord3 = FieldsList.None;
		
        /// <summary> 
        /// Gets or sets the third Order value.
        /// </summary>
        /// <value> FileName</value>
        [XmlAttribute]
        public FieldsList Ord3
        {
            [DebuggerStepThrough]
            get { return this.ord3; }
            [DebuggerStepThrough]
            set { this.ord3 = value; }
        }
		
        /// <summary>
        /// Sets the Ord3 value.
        /// </summary>
        /// <param name="ord3">The ord3.</param>
        /// <returns></returns>
        public WLTableFilter SetOrd3 (FieldsList ord3)
        {
            this.ord3 = ord3;
            return this; 
        }
		
        public enum FieldsList : byte
        {
            None = 0, 
            Id = 1, 
            Number = 2, 
            WaiterWLEmployeeId = 3, 
            ManagerWLEmployeeId = 4, 
            WLLocationId = 5, 
            WLDictServiceDeviceId = 6, 
            BeachButlerWhoToPage = 7, 
            TGLeftButtonWhoToPage = 8, 
            TGMiddleButtonWhoToPage = 9, 
            TGRightButtonWhoToPage = 10, 
            SerialNo = 11, 
            WLTableId = 12, 
            ClientId = 13, 
            WLDictChangeStatusId = 14			
        }
	
	
    }
}

// end of namespace

